/* Spanish — the application's own text.
 *
 * Small, and always loaded, because these strings are the interface itself: the
 * step headings, the buttons, the beginner guide, the GM tools. The book's rules
 * text is the large half and lives in es-book.js, fetched only when somebody
 * actually asks for Spanish.
 *
 * Keys are the English exactly as it reaches the screen, so a key that stops
 * matching falls back to English rather than showing a translation of something
 * the application no longer says. Digit runs are written {0}, {1}… so one entry
 * covers a whole family of interpolated strings.
 *
 * What is deliberately NOT translated, and must not be: class, archetype, feat,
 * background and gear NAMES. Characters are stored keyed on those exact English
 * strings, and armourClass(), weaponProficient() and the action-economy
 * classifier all read English prose, so translating them would break saved
 * sheets and shared links. They stay English on purpose — the same way a
 * Spanish-speaking table playing from an English book keeps them.
 *
 * Machine translated, with the mechanical vocabulary (CD, PG, competencia,
 * ventaja, salvacion) settled by hand. The English is the reference text.
 */
window.TTES = window.TTES || {};
window.TTES.ui = {
  "+ Ad-hoc": "+ Improvisado",
  "+ Blank NPC": "+ PNJ en blanco",
  "+ New campaign": "+ Campaña nueva",
  "+ Party": "+ Grupo",
  "+ Quick mook": "+ Esbirro rápido",
  "+ {0}-segment clock": "+ reloj de {0} segmentos",
  ", tools, starting gear and a special ability. Your origin is where you came from, and gives a small perk plus a story hook.": ", herramientas, equipo inicial y una capacidad especial. Tu origen es de dónde vienes, y da una pequeña ventaja más un gancho narrativo.",
  ". The money is your DM's problem. The Humanity is yours: each implant takes a piece of the person you were, and at zero your character is gone.": ". El dinero es problema de tu DM. La Humanidad es tuya: cada implante se lleva un trozo de la persona que eras, y a cero pierdes al personaje.",
  ": raise your numbers, or take a": ": subir tus números, o tomar una",
  "A Fixer does this with Favours instead of a roll. Let them.": "Un Fixer hace esto con Favores en lugar de una tirada. Déjale.",
  "A Fraying character takes a crit or drops to {0}": "Un personaje Deshilachado recibe un crítico o cae a {0}",
  "A [[skill]] is something you roll for outside combat. Being trained in one means adding your [[proficiency bonus]] to that roll, which is a big deal.": "Una [[skill|habilidad]] es algo que tiras fuera del combate. Tener competencia en una significa sumar tu [[proficiency bonus|bonificador de competencia]] a esa tirada, que es mucho.",
  "A background says what you did for money. An origin says what was done to you first. Take one of each — they answer different questions.": "Un trasfondo dice a qué te dedicabas por dinero. Un origen dice qué te hicieron antes de eso. Coge uno de cada — responden a preguntas distintas.",
  "A cheap padlock": "Un candado barato",
  "A link that rebuilds this exact character for whoever opens it": "Un enlace que reconstruye este mismo personaje para quien lo abra",
  "A number that grows with your level (+{0} at {1}st, +{2} at {3}th). You add it to anything you're trained in.": "Un número que crece con tu nivel (+{0} a nivel {1}, +{2} a nivel {3}). Lo sumas a todo aquello en lo que tengas competencia.",
  "A quick extra thing, only when a feature says you can. One per turn, on top of your action.": "Algo extra y rápido, solo cuando un rasgo diga que puedes. Una por turno, además de tu acción.",
  "A roll to resist something happening to you — poison, an explosion, mind control. Your class is trained in two of them.": "Una tirada para resistir algo que te ocurre — veneno, una explosión, control mental. Tu clase tiene competencia en dos de ellas.",
  "A running long jump clears feet equal to Strength score with no roll. Only roll past that.": "Un salto de longitud con carrera cubre tantos pies como tu puntuación de Fuerza sin tirar. Solo se tira para pasar de ahí.",
  "A safe jack-out needs no roll. This is for when something has hold of them.": "Desconectarse con seguridad no requiere tirada. Esto es para cuando algo les tiene agarrados.",
  "A special package of abilities you can take instead of raising your ability scores.": "Un paquete especial de capacidades que puedes tomar en vez de subir tus puntuaciones de característica.",
  "A specialisation inside your class — the flavour of Rogue or Wirewalker you are. Also called a subclass.": "Una especialización dentro de tu clase — el tipo de Rogue o de Wirewalker que eres. También se llama subclase.",
  "A specialist's day at work.": "Un día normal para un especialista.",
  "A thing you can be trained in, like Stealth or Persuasion. Roll a d{0}, add the matching ability modifier, and add your proficiency bonus if you're trained.": "Algo en lo que puedes tener competencia, como Sigilo o Persuasión. Tira un d{0}, suma el modificador de característica correspondiente y suma tu bonificador de competencia si tienes competencia.",
  "A trained hand barely notices.": "Una mano entrenada apenas lo nota.",
  "Abilities": "Características",
  "Abilities & saves": "Características y salvaciones",
  "Ability cards": "Tarjetas de rasgos",
  "Ability check": "Prueba de característica",
  "Ability increase": "Mejora de característica",
  "Ability score improvements": "Mejoras de puntuación de característica",
  "Ability scores": "Puntuaciones de característica",
  "About an hour. You recover some abilities, and can spend Hit Dice to heal.": "Una hora aproximadamente. Recuperas algunas capacidades y puedes gastar Dados de Golpe para curarte.",
  "About eight hours of downtime. You get your health and most abilities back.": "Unas ocho horas de descanso. Recuperas la salud y casi todas tus capacidades.",
  "Acrobatics": "Acrobacias",
  "Action": "Acción",
  "Actions": "Acciones",
  "Add": "Añadir",
  "Add the party, then drop in whatever they've walked into.": "Añade al grupo y luego mete aquello con lo que se han topado.",
  "Add to party": "Añadir al grupo",
  "Altering is harder than deleting. Deleting is conspicuous. Neither is clean.": "Alterar es más difícil que borrar. Borrar canta. Ninguna de las dos es limpia.",
  "An ICE program hits them": "Un programa ICE les alcanza",
  "An [[archetype]] is a specialisation inside your class. Two Rogues can play completely differently depending on which one they took.": "Un [[archetype|arquetipo]] es una especialización dentro de tu clase. Dos Rogues pueden jugarse de forma totalmente distinta según cuál hayan cogido.",
  "Animal Handling": "Trato con Animales",
  "Any situation": "Cualquier situación",
  "Anyone not actively hindered.": "Cualquiera que no tenga un impedimento real.",
  "Anything your background already gave you is ticked and can't be picked twice.": "Lo que ya te dio tu trasfondo aparece marcado y no se puede elegir dos veces.",
  "Arcana": "Arcanos",
  "Archetype": "Arquetipo",
  "Armor Class": "Clase de Armadura",
  "Artificer Infusions": "Infusiones de artificiero",
  "Ask each player to open their Play Sheet, hit Copy share link, and send it to you. Paste it above.": "Pide a cada jugador que abra su Hoja de juego, pulse Copiar enlace para compartir y te lo mande. Pégalo arriba.",
  "At levels {0}, {1}, {2}, {3} and {4} every character gets an": "En los niveles {0}, {1}, {2}, {3} y {4} todo personaje recibe una",
  "At levels {0}, {1}, {2}, {3} and {4} every character gets an [[ability score improvement]]: raise your numbers, or take a [[feat]] instead. Some classes also learn new things as they level.": "En los niveles {0}, {1}, {2}, {3} y {4} todo personaje recibe una [[ability score improvement|mejora de puntuación de característica]]: subir tus números, o tomar una [[feat|dote]] en su lugar. Algunas clases además aprenden cosas nuevas al subir de nivel.",
  "At levels {0}, {1}, {2}, {3} and {4} you either raise your ability scores or take a feat. Often shortened to ASI.": "En los niveles {0}, {1}, {2}, {3} y {4} subes tus puntuaciones de característica o tomas una dote. Se suele abreviar ASI.",
  "Athletics": "Atletismo",
  "Athletics to overpower, Acrobatics to slip. Rope and cuffs are Sleight of Hand against a flat DC.": "Atletismo para imponerse, Acrobacias para escurrirse. Cuerdas y esposas son Juego de Manos contra una CD fija.",
  "Attack": "Ataque",
  "Augments": "Mejoras",
  "Augments · {0}": "Mejoras · {0}",
  "Back": "Atrás",
  "Background": "Trasfondo",
  "Background & origin": "Trasfondo y origen",
  "Background · {0} from the book": "Trasfondo · {0} del libro",
  "Backgrounds": "Trasfondos",
  "Backgrounds are as much about story as numbers. Pick one you'd enjoy explaining to the table.": "Los trasfondos son tanto historia como números. Elige uno que te apetezca explicar en la mesa.",
  "Bank-grade, or under time pressure": "De grado bancario, o con el tiempo en contra",
  "Base {0} (Cha × {1})  ·  {2} implant · −{3}  ·  Humanity {4} / {5}": "Base {0} (Car × {1})  ·  {2} implante · −{3}  ·  Humanidad {4} / {5}",
  "Beginner guide": "Guía para principiantes",
  "Beginner guide off": "Guía para principiantes desactivada",
  "Best of three rolls over three rounds beats one roll. Let Acrobatics cover the obstacles.": "Mejor de tres tiradas en tres asaltos que una sola tirada. Deja que Acrobacias cubra los obstáculos.",
  "Bonus action": "Acción adicional",
  "Bonus actions": "Acciones adicionales",
  "Book p. {0}": "Libro p. {0}",
  "Break out of a grapple or restraints": "Zafarse de un agarre o de unas ataduras",
  "Bring dice, or an app.": "Trae dados, o una aplicación.",
  "Brings their names and notes over. You add the numbers.": "Trae sus nombres y sus notas. Los números los pones tú.",
  "Build order": "Orden de creación",
  "Campaign": "Campaña",
  "Cancel": "Cancelar",
  "Cha": "Car",
  "Cha (Deception)": "Car (Engaño)",
  "Cha (Intimidation)": "Car (Intimidación)",
  "Cha (Persuasion)": "Car (Persuasión)",
  "Change": "Cambiar",
  "Character level": "Nivel del personaje",
  "Character name": "Nombre del personaje",
  "Charisma": "Carisma",
  "Charisma save": "salvación de Carisma",
  "Charisma score": "puntuación de Carisma",
  "Check the vitals strip — that's your": "Mira la franja de constantes — ahí tienes tus",
  "Check the vitals strip — that's your [[armour class|AC]], [[hit points]], [[initiative]] and [[proficiency bonus]].": "Mira la franja de constantes — ahí tienes tu [[armour class|CA]], tus [[hit points|puntos de golpe]], tu [[initiative|iniciativa]] y tu [[proficiency bonus|bonificador de competencia]].",
  "Choose a class": "Elige una clase",
  "Choose an archetype": "Elige un arquetipo",
  "Choose {0} more skill.": "Elige {0} habilidad más.",
  "Choose {0} more skills.": "Elige {0} habilidades más.",
  "Chosen": "Elegido",
  "Chrome": "Cromo",
  "Chrome & Gear": "Cromo y equipo",
  "Chrome & gear": "Cromo y equipo",
  "Chrome & gear · {0},{1}₵": "Cromo y equipo · {0},{1}₵",
  "Church of the Signal origin senses surveillance": "El origen Iglesia de la Señal percibe la vigilancia",
  "Class": "Clase",
  "Classic sheet": "Hoja clásica",
  "Clear": "Limpiar",
  "Climb something without gear": "Escalar algo sin equipo",
  "Clocks": "Relojes",
  "Close": "Cerrar",
  "Codex": "Códice",
  "Collapse all": "Plegar todo",
  "Compliance now, a grudge later, and a description given to someone who pays for them.": "Obedecen ahora, guardan rencor después, y le dan tu descripción a alguien que paga por ella.",
  "Con": "Con",
  "Con/Cha": "Con/Car",
  "Con/Cha saves": "salvaciones Con/Car",
  "Con/Int": "Con/Int",
  "Con/Int saves": "salvaciones Con/Int",
  "Condition": "Estado",
  "Conditions": "Estados",
  "Constitution": "Constitución",
  "Constitution is never a bad place for a good number — it's your health and it matters for every class.": "Constitución nunca es mal sitio para un número alto — es tu salud y le importa a todas las clases.",
  "Constitution save": "salvación de Constitución",
  "Constitution score": "puntuación de Constitución",
  "Consumer kit": "Gama de consumo",
  "Contest against their Insight, or use passive Insight if they aren't suspicious yet.": "Enfréntalo a su Perspicacia, o usa la Perspicacia pasiva si todavía no sospechan.",
  "Copy": "Copiar",
  "Copy as Markdown": "Copiar como Markdown",
  "Copy share link": "Copiar enlace para compartir",
  "Copy sheet & finish": "Copiar la hoja y terminar",
  "Custom Gear": "Equipo propio",
  "Cyberware": "Ciberware",
  "Cyberware costs": "Coste del ciberware",
  "Cyberware costs [[credits|money]] and [[humanity]]. The money is your DM's problem. The Humanity is yours: each implant takes a piece of the person you were, and at zero your character is gone.": "El ciberware cuesta [[credits|dinero]] y [[humanity|humanidad]]. El dinero es problema de tu DM. La Humanidad es tuya: cada implante se lleva un trozo de la persona que eras, y a cero pierdes al personaje.",
  "Cyberware is rated by tier — higher tiers cost exponentially more credits and more of you. Every implant shows what it takes off your Humanity.": "El ciberware se clasifica por niveles — los niveles altos cuestan exponencialmente más créditos y más de ti. Cada implante indica cuánto te quita de Humanidad.",
  "Cyberware · {0} implants": "Ciberware · {0} implantes",
  "DC {0}": "CD {0}",
  "DC {0} flat, an action, and it doesn't restore hit points. A Streetdoc has better options.": "CD {0} fija, una acción, y no devuelve puntos de golpe. Un Streetdoc tiene mejores opciones.",
  "DC {0} · easy": "CD {0} · fácil",
  "DC {0} · extreme": "CD {0} · extremo",
  "DC {0} · hard": "CD {0} · difícil",
  "DC {0} · moderate": "CD {0} · moderado",
  "DC {0} · trivial": "CD {0} · trivial",
  "Damage": "Daño",
  "Damage taken in the NET is real. The body in the chair is what the crew is standing over.": "El daño recibido en la NET es real. El cuerpo de la silla es lo que el equipo tiene delante.",
  "Deception": "Engaño",
  "Delete": "Borrar",
  "Dex": "Des",
  "Dex (Sleight of Hand)": "Des (Juego de Manos)",
  "Dex/Cha": "Des/Car",
  "Dex/Cha saves": "salvaciones Des/Car",
  "Dex/Int": "Des/Int",
  "Dex/Int saves": "salvaciones Des/Int",
  "Dexterity": "Destreza",
  "Dexterity save": "salvación de Destreza",
  "Dexterity score": "puntuación de Destreza",
  "Dexterity, Intelligence": "Destreza, Inteligencia",
  "Difficulty Class — the number you need to meet or beat on a roll. Your own DC is what enemies must beat to resist your abilities.": "Clase de Dificultad — el número que tienes que igualar o superar en una tirada. Tu propia CD es la que los enemigos deben superar para resistir tus capacidades.",
  "Disable an alarm or camera": "Desactivar una alarma o una cámara",
  "Divine industry · Body horror · House politics · Vertical city": "Industria divina · Terror corporal · Política de casas · Ciudad vertical",
  "Don't try to memorise it. Everyone reads their sheet at the table, including people who've played for years.": "No intentes memorizarlo. Todo el mundo lee su hoja en la mesa, incluida la gente que lleva años jugando.",
  "Done": "Hecho",
  "Download .md": "Descargar .md",
  "Download backup (.json)": "Descargar copia de seguridad (.json)",
  "Drive hard — evade, ram, or take a corner too fast": "Conducir al límite — esquivar, embestir o tomar una curva demasiado rápido",
  "Each opens a preview first, so you can see the page before you spend the paper. Use your browser's “Save as PDF” in the print dialog if you'd rather have a file.": "Cada uno abre primero una vista previa, para que veas la página antes de gastar papel. Usa «Guardar como PDF» en el diálogo de impresión de tu navegador si prefieres un archivo.",
  "Easiest option — recommended if you're new": "La opción más fácil — recomendada si empiezas",
  "Easy {0}": "Fácil {0}",
  "Edit": "Editar",
  "Encounter": "Encuentro",
  "Equipment": "Equipo",
  "Every class offers a choice of archetypes — pick the one you want to play.": "Cada clase ofrece varios arquetipos — elige el que quieras jugar.",
  "Every feature as a cut-out card.": "Cada rasgo como una tarjeta recortable.",
  "Every level you cross hands you something. Rogue ability score improvements arrive at {0}th, {1}th, {2}th, {3}th, {4}th and {5}th — take the increase or a feat instead. Classes that learn things as they go pick them here too.": "Cada nivel que cruzas te da algo. Las mejoras de característica de Rogue llegan en los niveles {0}, {1}, {2}, {3}, {4} y {5} — coge la mejora o una dote en su lugar. Las clases que van aprendiendo cosas también las eligen aquí.",
  "Every number a player is about to be asked for. Sheets arrive as the share codes they already make — this is a snapshot, so ask for a fresh one when someone levels.": "Todos los números que vas a pedirle a un jugador. Las hojas llegan como los códigos para compartir que ya generan — esto es una instantánea, así que pide una nueva cuando alguien suba de nivel.",
  "Everyone you might need numbers for. Mooks are one line; anyone who matters gets the full block.": "Todo aquel de quien puedas necesitar números. Los esbirros ocupan una línea; quien importa lleva bloque completo.",
  "Everything on screen, printed straight through.": "Todo lo que hay en pantalla, impreso de principio a fin.",
  "Everything's filled in. Open the play sheet to print or copy your character.": "Ya está todo relleno. Abre la hoja de juego para imprimir o copiar tu personaje.",
  "Example build": "Personaje de ejemplo",
  "Expand all": "Desplegar todo",
  "Expansion Classes": "Clases de la expansión",
  "Expertise plus luck.": "Pericia y además suerte.",
  "Export": "Exportar",
  "Export GM vault": "Exportar la caja del DM",
  "Export all": "Exportar todo",
  "Export this campaign": "Exportar esta campaña",
  "Extreme {0}": "Extremo {0}",
  "Failure by {0} or more trips the alarm rather than just refusing.": "Fallar por {0} o más dispara la alarma en vez de limitarse a no ceder.",
  "Favours on the book replace payment. Write down who holds it — the book is a real object and someone keeps it.": "Los favores anotados en el libro sustituyen al pago. Apunta quién lo tiene — el libro es un objeto real y alguien lo guarda.",
  "Feat": "Dote",
  "Feats": "Dotes",
  "Feats are more interesting but ability increases are more reliably useful. There's no shame in +{0} Dexterity.": "Las dotes son más interesantes, pero las mejoras de característica son más fiables. No pasa nada por un +{0} a Destreza.",
  "Features unlock as you level. Drag the level slider in the panel on the right to see what arrives later.": "Los rasgos se desbloquean al subir de nivel. Mueve el deslizador de nivel del panel derecho para ver qué llega después.",
  "Fence something hot": "Colocar algo robado",
  "Field surgery, or pull ware loose": "Cirugía de campo, o arrancar ware",
  "Fighting Styles": "Estilos de combate",
  "Filter Artificer Infusions": "Filtrar Infusiones de artificiero",
  "Filter Augments": "Filtrar Mejoras",
  "Filter Backgrounds": "Filtrar Trasfondos",
  "Filter Cyberware": "Filtrar Ciberware",
  "Filter Expansion Classes": "Filtrar Clases de la expansión",
  "Filter Feats": "Filtrar Dotes",
  "Filter Fighting Styles": "Filtrar Estilos de combate",
  "Filter Glossary": "Filtrar Glosario",
  "Filter Humanity & Cred": "Filtrar Humanidad y Reputación",
  "Filter Origins": "Filtrar Orígenes",
  "Filter Reference Tables": "Filtrar Tablas de referencia",
  "Filter Subclasses": "Filtrar Subclases",
  "Filter Warlock Invocations": "Filtrar Invocaciones de brujo",
  "Filter artificer infusions…": "Filtrar infusiones de artificiero…",
  "Filter augments…": "Filtrar mejoras…",
  "Filter backgrounds…": "Filtrar trasfondos…",
  "Filter chrome and gear": "Filtrar cromo y equipo",
  "Filter cyberware…": "Filtrar ciberware…",
  "Filter expansion classes…": "Filtrar clases de la expansión…",
  "Filter feats…": "Filtrar dotes…",
  "Filter fighting styles…": "Filtrar estilos de combate…",
  "Filter glossary…": "Filtrar glosario…",
  "Filter humanity & cred…": "Filtrar humanidad y reputación…",
  "Filter implants, augments and gear…": "Filtrar implantes, mejoras y equipo…",
  "Filter origins…": "Filtrar orígenes…",
  "Filter reference tables…": "Filtrar tablas de referencia…",
  "Filter subclasses…": "Filtrar subclases…",
  "Filter warlock invocations…": "Filtrar invocaciones de brujo…",
  "Find a way through a district they don't know": "Orientarse en un distrito que no conocen",
  "Find out what the street knows": "Averiguar lo que se sabe en la calle",
  "Firearm rule": "Regla de armas de fuego",
  "Firearms": "Armas de fuego",
  "Follow someone through a crowd without being made": "Seguir a alguien entre la multitud sin que te descubran",
  "Forge": "Forja",
  "Forge or spoof a credential": "Falsificar o suplantar una credencial",
  "From a file": "Desde un archivo",
  "From a template": "Desde una plantilla",
  "From the book · {0} classes": "Del libro · {0} clases",
  "Full dossier": "Dosier completo",
  "Gear": "Equipo",
  "Get clear of a blast": "Apartarse de una explosión",
  "Get it off the screen.": "Sácalo de la pantalla.",
  "Glossary": "Glosario",
  "Good first class": "Buena clase para empezar",
  "Good first ones for Cathedra: “The Cantor notices you”, “House Thorn calls the debt”, “The god turns its head”.": "Buenos primeros para Cathedra: «El Cantor se fija en ti», «La Casa Thorn reclama la deuda», «El dios vuelve la cabeza».",
  "Granted by your background": "Otorgado por tu trasfondo",
  "HP": "PG",
  "Hack a door panel or terminal": "Hackear un panel de puerta o un terminal",
  "Haggle a price": "Regatear un precio",
  "Half damage on a success unless the source says otherwise.": "La mitad de daño si se tiene éxito, salvo que la fuente diga otra cosa.",
  "Halfway, and stuck. Falling is the second failure, not the first.": "A medio camino y atascado. Caerse es el segundo fallo, no el primero.",
  "Hard {0}": "Difícil {0}",
  "Heal": "Curar",
  "Hide guide": "Ocultar guía",
  "History": "Historia",
  "Hit": "Dado",
  "Hit d{0}": "Dado d{0}",
  "Hit points": "Puntos de golpe",
  "Hold it together in front of something awful": "Mantener la compostura ante algo espantoso",
  "Hooks": "Ganchos",
  "House Rules": "Reglas de la casa",
  "House rule. A fall in Cathedra is a change of scene.": "Regla de la casa. Una caída en Cathedra es un cambio de escena.",
  "House rule. A held favour should come back in a later session, unprompted.": "Regla de la casa. Un favor pendiente debería volver en una sesión posterior, sin que nadie lo pida.",
  "House rule. It's absolute, not a DC. Say so before they commit to a plan built on it.": "Regla de la casa. Es absoluto, no una CD. Dilo antes de que monten un plan encima.",
  "House rule. The Clocks screen is the right place to track what comes of it.": "Regla de la casa. La pantalla de Relojes es el sitio para seguir lo que salga de esto.",
  "House rule. The Remnant is yours to invent. Make it a person, not a debuff.": "Regla de la casa. El Remanente te lo inventas tú. Que sea una persona, no una penalización.",
  "How advanced a piece of cyberware is, {0} to {1}. Higher tiers are stronger, cost far more credits, and cost more Humanity.": "Lo avanzada que es una pieza de ciberware, de {0} a {1}. Los niveles altos son más potentes, cuestan muchos más créditos y más Humanidad.",
  "How hard you are to hit. An attacker must roll this number or higher on a d{0}. Usually written AC.": "Lo difícil que eres de acertar. Quien te ataca tiene que sacar este número o más en un d{0}. Se suele escribir CA.",
  "Humanity": "Humanidad",
  "Humanity & Cred": "Humanidad y Reputación",
  "Humanity — every implant is a piece of you that used to be meat": "Humanidad — cada implante es un trozo de ti que antes era carne",
  "Identify what chrome someone is running": "Identificar qué cromo lleva alguien",
  "If the check is against a machine rather than a person, use Technology instead.": "Si la prueba es contra una máquina y no contra una persona, usa Tecnología.",
  "If you're proficient with simple or martial weapons, you're proficient with simple or martial firearms. Some classes get extra firearms on top — see the table below.": "Si tienes competencia con armas simples o marciales, la tienes con armas de fuego simples o marciales. Algunas clases reciben armas de fuego adicionales — mira la tabla de abajo.",
  "If your class learns programs, grafts or imprints, pick them here — the count grows every few levels.": "Si tu clase aprende programas, injertos o improntas, elígelos aquí — la cuenta crece cada pocos niveles.",
  "Import": "Importar",
  "Import .json": "Importar .json",
  "Import a share link on the Party screen.": "Importa un enlace compartido en la pantalla de Grupo.",
  "Import the party first.": "Importa primero al grupo.",
  "Improvise someone": "Improvisar a alguien",
  "In play": "En juego",
  "Init": "Ini",
  "Initiative": "Iniciativa",
  "Initiative order": "Orden de iniciativa",
  "Initiative, hit points and conditions. Tap a bar to damage or heal.": "Iniciativa, puntos de golpe y estados. Toca una barra para dañar o curar.",
  "Insight": "Perspicacia",
  "Install one or two": "Instala uno o dos",
  "Install one or two [[tier|tier {0}]] implants to start. They're cheap in both currencies.": "Instala uno o dos implantes de [[tier|nivel {0}]] para empezar. Son baratos en las dos monedas.",
  "Installed · {0},{1}₵": "Instalado · {0},{1}₵",
  "Int": "Int",
  "Int (Investigation)": "Int (Investigación)",
  "Int (Technology)": "Int (Tecnología)",
  "Int/Wis": "Int/Sab",
  "Int/Wis saves": "salvaciones Int/Sab",
  "Intelligence": "Inteligencia",
  "Intelligence save": "salvación de Inteligencia",
  "Intelligence score": "puntuación de Inteligencia",
  "Intimidation": "Intimidación",
  "Investigation": "Investigación",
  "Investigation if they're working records, Persuasion if they're working people. Both take hours.": "Investigación si trabajan los archivos, Persuasión si trabajan a la gente. Las dos cuestan horas.",
  "Investigation, Technology, Stealth, Perception, Sleight of Hand, Deception": "Investigación, Tecnología, Sigilo, Percepción, Juego de Manos, Engaño",
  "It comes out. So does something that was holding them together.": "Sale. Y con ello algo que les mantenía de una pieza.",
  "It doesn't work. No netrunning, no smartlink, no comms — and powered cyberware operates at disadvantage while they stand there.": "No funciona. Ni netrunning, ni smartlink, ni comunicaciones — y el ciberware con corriente opera con desventaja mientras estén ahí.",
  "It goes quiet locally and reports the outage upstream.": "Se calla en local y notifica el corte aguas arriba.",
  "It installs at +{0} Humanity over the listed cost, and it carries a Remnant — something of the last owner comes with it.": "Se instala con +{0} de Humanidad sobre el coste indicado, y trae un Remanente — algo del anterior dueño viene con ello.",
  "It scans clean now and flags on the overnight audit.": "Ahora pasa el escáner limpio y salta en la auditoría nocturna.",
  "It's visible": "Se nota a simple vista",
  "Jack out under pressure": "Desconectarse bajo presión",
  "Jump a gap": "Saltar un hueco",
  "Keep a straight face when something goes wrong": "No cambiar la cara cuando algo sale mal",
  "Keep up in a foot chase": "Aguantar una persecución a pie",
  "Ladder rungs, cargo netting, a fire escape": "Peldaños de escalera, red de carga, una escalera de incendios",
  "Languages": "Idiomas",
  "Lean on someone": "Presionar a alguien",
  "Level": "Nivel",
  "Level ladder": "Escalera de niveles",
  "Level up: {0} ability/feat choice to pick": "Subida de nivel: queda {0} decisión de característica o dote",
  "Level up: {0} ability/feat choices to pick": "Subida de nivel: quedan {0} decisiones de característica o dote",
  "Level {0}": "Nivel {0}",
  "Level {0} Rogue · Saboteur · Hacker": "Rogue de nivel {0} · Saboteur · Hacker",
  "Level-Ups": "Subidas de nivel",
  "Level-up choices": "Decisiones de subida de nivel",
  "Lock GM tools": "Bloquear herramientas del DM",
  "Look it up ({0} situations)": "Consultarlo ({0} situaciones)",
  "Lv {0}": "Niv {0}",
  "Manual": "Manual",
  "Medicine": "Medicina",
  "Military or bank": "Militar o bancario",
  "Military-grade, or actively monitored": "De grado militar, o vigilado en tiempo real",
  "Moderate {0}": "Moderado {0}",
  "Money in this setting, written ₵. Cyberware is expensive; tier {0} runs to tens of millions.": "El dinero de esta ambientación, se escribe ₵. El ciberware es caro; el nivel {0} llega a decenas de millones.",
  "Move past a guard unseen": "Pasar junto a un guardia sin ser visto",
  "Move the level slider, and the app will tell you exactly what you gained and what you still need to choose.": "Mueve el deslizador de nivel y la aplicación te dirá exactamente qué has ganado y qué te queda por elegir.",
  "NPCs": "PNJ",
  "Name": "Nombre",
  "Name your operator": "Ponle nombre a tu operador",
  "Names you invented, promises made, what to open with next time…": "Nombres que te inventaste, promesas hechas, con qué empezar la próxima…",
  "Nature": "Naturaleza",
  "Near-impossible {0}": "Casi imposible {0}",
  "Needs thieves' tools. No proficiency means no roll at all on anything above easy.": "Requiere herramientas de ladrón. Sin competencia no hay tirada en nada que pase de fácil.",
  "Neon Ledger expansion · {0} classes": "Expansión Neon Ledger · {0} clases",
  "Neon Ledger · pick one or roll a d{0}": "Neon Ledger · elige uno o tira un d{0}",
  "Never exported. Everything here lives in this browser only — clearing site data deletes it.": "Nunca se exporta. Todo esto vive solo en este navegador — si borras los datos del sitio, desaparece.",
  "New character": "Personaje nuevo",
  "New to this? Background and origin": "¿Es tu primera vez? Trasfondo y origen",
  "New to this? Buying chrome": "¿Es tu primera vez? Comprar cromo",
  "New to this? Levelling up": "¿Es tu primera vez? Subir de nivel",
  "New to this? Skills and proficiency": "¿Es tu primera vez? Habilidades y competencia",
  "New to this? What a class is": "¿Es tu primera vez? Qué es una clase",
  "New to this? What an archetype is": "¿Es tu primera vez? Qué es un arquetipo",
  "New to this? What the six numbers mean": "¿Es tu primera vez? Qué significan los seis números",
  "New to this? Your character sheet": "¿Es tu primera vez? Tu hoja de personaje",
  "Next": "Siguiente",
  "Next level up": "Próxima subida de nivel",
  "Next thing to do": "Lo siguiente que hacer",
  "No NPCs yet.": "Aún no hay PNJ.",
  "No Vehicles skill in this book. Technology for anything driven, Athletics if they're hanging off it.": "En este libro no hay habilidad de Vehículos. Tecnología para todo lo que se conduzca, Atletismo si van colgando de ello.",
  "No clocks running.": "No hay relojes en marcha.",
  "No encounter running.": "No hay ningún encuentro en marcha.",
  "No one at the table yet.": "Todavía no hay nadie en la mesa.",
  "Not spotted outright — heard. They call it in and start walking your way.": "No te ven del todo — te oyen. Lo notifican y empiezan a caminar hacia ti.",
  "Notes": "Notas",
  "Nothing in the initiative order.": "No hay nada en el orden de iniciativa.",
  "Nothing saved yet. Hit Save to roster above.": "Todavía no has guardado nada. Pulsa Guardar en el archivo, arriba.",
  "Notice an ambush": "Detectar una emboscada",
  "Notice they're being followed": "Darse cuenta de que les siguen",
  "Nyx Calderón is loaded so you can see a finished sheet. Change anything — or hit": "Nyx Calderón viene cargada para que veas una hoja terminada. Cambia lo que quieras — o pulsa",
  "On this step": "En este paso",
  "On your turn you get one": "En tu turno tienes una",
  "One of six numbers (Strength, Dexterity, Constitution, Intelligence, Wisdom, Charisma) rating your body and mind. {0} is average for a person; {1} is the human peak.": "Uno de los seis números (Fuerza, Destreza, Constitución, Inteligencia, Sabiduría, Carisma) que miden tu cuerpo y tu mente. {0} es la media de una persona; {1} es el máximo humano.",
  "One small card with your vitals and turn options.": "Una tarjeta pequeña con tus constantes y tus opciones de turno.",
  "Only at Humanity {0}-{1}%. On a failure they attack the nearest creature — nearest, not an enemy.": "Solo con Humanidad {0}-{1}%. Si fallan, atacan a la criatura más cercana — la más cercana, no un enemigo.",
  "Open": "Abrir",
  "Open in forge": "Abrir en la forja",
  "Open play sheet": "Abrir hoja de juego",
  "Optional — but most characters want a weapon at least.": "Opcional — pero casi todos los personajes quieren al menos un arma.",
  "Options": "Opciones",
  "Origin": "Origen",
  "Origin perk, Wisdom (Perception) DC {0}, and only for that origin. They can always attempt it.": "Ventaja de origen, Sabiduría (Percepción) CD {0}, y solo para ese origen. Siempre pueden intentarlo.",
  "Out, but stunned until the end of their next turn.": "Fuera de combate, pero aturdido hasta el final de su siguiente turno.",
  "Overview": "Resumen",
  "Party": "Grupo",
  "Party ({0})": "Grupo ({0})",
  "Passive": "Pasiva",
  "Passive Perception": "Percepción pasiva",
  "Paste a share link, or the code from one": "Pega un enlace compartido, o el código de uno",
  "Perception": "Percepción",
  "Perception is the most-rolled skill in the game. If it's on your class list and nobody else has it, take it.": "Percepción es la habilidad que más se tira del juego. Si está en la lista de tu clase y no la tiene nadie más, cógela.",
  "Perception is what they notice walking in. Investigation is what they find when they take ten minutes.": "Percepción es lo que notan al entrar. Investigación es lo que encuentran si dedican diez minutos.",
  "Performance": "Interpretación",
  "Persuasion": "Persuasión",
  "Pick a mechanical lock": "Forzar una cerradura mecánica",
  "Pick a weapon and some armour from the tables lower down.": "Elige un arma y algo de armadura en las tablas de más abajo.",
  "Pick one background. If it says “choose two from…”, buttons will appear for you to choose.": "Elige un trasfondo. Si pone «elige dos de…», aparecerán botones para que elijas.",
  "Pick or roll an origin — the d{0} button rolls for you.": "Elige o tira un origen — el botón d{0} tira por ti.",
  "Pick the number of skills your class allows — the counter at the top tracks it.": "Elige tantas habilidades como permita tu clase — el contador de arriba lo lleva.",
  "Plain-English definitions for the words this app and the rules use. Dotted words inside the beginner guide open these too.": "Definiciones claras de las palabras que usan esta aplicación y las reglas. Las palabras subrayadas de la guía para principiantes también las abren.",
  "Play Sheet": "Hoja de juego",
  "Player's name (optional)": "Nombre del jugador (opcional)",
  "Pocket card": "Tarjeta de bolsillo",
  "Point buy": "Compra por puntos",
  "Point buy, the standard array, rolled, or typed straight in. These are your starting scores — ability score improvements and class features add to them, shown in green.": "Compra por puntos, reparto estándar, tiradas, o escritos a mano. Estas son tus puntuaciones iniciales — las mejoras de característica y los rasgos de clase suman encima, y se ven en verde.",
  "Prereq: vicious mockery cantrip": "Requisito: truco burla viciosa",
  "Prereq: {0}rd level.": "Requisito: nivel {0}.",
  "Prereq: {0}th level": "Requisito: nivel {0}",
  "Prereq: {0}th-level artificer": "Requisito: artificiero de nivel {0}",
  "Print": "Imprimir",
  "Print it, or copy it as Markdown and paste it wherever you keep notes.": "Imprímela, o cópiala como Markdown y pégala donde guardes tus notas.",
  "Print preview · {0}": "Vista previa de impresión · {0}",
  "Print sheet": "Imprimir hoja",
  "Prof": "Comp",
  "Professionals check their tail at corners. Ask for a new roll each time they do.": "Los profesionales miran atrás en cada esquina. Pide una tirada nueva cada vez que lo hagan.",
  "Proficiencies": "Competencias",
  "Proficiency": "Competencia",
  "Proficiency bonus": "Bonificador de competencia",
  "Pull {0} from Cathedra": "Sacar {0} de Cathedra",
  "Put your {0} in the ability marked as your class's primary — it's highlighted for you.": "Pon tu {0} en la característica marcada como principal de tu clase — te la hemos resaltado.",
  "Put {0} and {1} in Constitution and whatever else your class leans on. Dump the {2} somewhere you don't care about.": "Pon {0} y {1} en Constitución y en aquello en lo que se apoye tu clase. Suelta el {2} donde no te importe.",
  "Reaction": "Reacción",
  "Reactions": "Reacciones",
  "Read the cards and pick whoever sounds like someone you'd enjoy being for a few months.": "Lee las fichas y elige a quien te apetezca ser durante unos meses.",
  "Read the features. Greyed-out ones are real — you just aren't high enough level yet.": "Lee los rasgos. Los que salen en gris son reales — lo que pasa es que aún no tienes nivel suficiente.",
  "Read whether someone is lying": "Averiguar si alguien está mintiendo",
  "Read “What you can do”. Those are your options on a turn, sorted by": "Lee «Lo que puedes hacer». Esas son tus opciones en un turno, ordenadas por",
  "Read “What you can do”. Those are your options on a turn, sorted by [[action]], [[bonus action]] and [[reaction]].": "Lee «Lo que puedes hacer». Esas son tus opciones en un turno, ordenadas por [[action|acción]], [[bonus action|acción adicional]] y [[reaction|reacción]].",
  "Ready": "Listo",
  "Reference Tables": "Tablas de referencia",
  "Religion": "Religión",
  "Remove": "Quitar",
  "Reset": "Reiniciar",
  "Resist a drug, toxin or gas": "Resistir una droga, toxina o gas",
  "Resist being moved, grabbed or knocked down": "Resistir un empujón, un agarre o un derribo",
  "Resource": "Recurso",
  "Rogue picks one of {0} archetypes at level {1}. Each has its own feature ladder at {2}rd, {3}th, {4}th, {5}th and {6}th level.": "Rogue elige uno de {0} arquetipos en el nivel {1}. Cada uno tiene su propia escalera de rasgos en los niveles {2}, {3}, {4}, {5} y {6}.",
  "Rogue picks {0} skills. Your background's skills are already counted and can't be picked twice.": "Rogue elige {0} habilidades. Las de tu trasfondo ya están contadas y no se pueden elegir dos veces.",
  "Roll": "Tirar",
  "Roll D{0}": "Tira D{0}",
  "Roll d{0}": "Tira d{0}",
  "Roll the attention die at the start of the session. On a {0} the god notices one character — use the button on the Party screen.": "Tira el dado de atención al empezar la sesión. Con un {0} el dios se fija en un personaje — usa el botón de la pantalla de Grupo.",
  "Roll two d{0}s and keep the higher one. Disadvantage is the same but you keep the lower.": "Tira dos d{0} y quédate con el más alto. La desventaja es igual pero te quedas con el más bajo.",
  "Roll {0}d{1}": "Tira {0}d{1}",
  "Roster": "Archivo",
  "Round": "Asalto",
  "Routed through a ghost relay": "Enrutado por un repetidor fantasma",
  "Ruling desk": "Mesa de arbitraje",
  "Rulings": "Arbitrajes",
  "Run by": "Dirige",
  "Save": "Guardar",
  "Save to roster": "Guardar en el archivo",
  "Saved in this browser · {0}": "Guardado en este navegador · {0}",
  "Saves": "Salvaciones",
  "Saving throw": "Tirada de salvación",
  "Saving throws": "Tiradas de salvación",
  "Say: “Roll Perception.”   DC {0} · moderate": "Di: «Tira Percepción».   CD {0} · moderado",
  "Scrub or alter a record": "Borrar o alterar un registro",
  "Search a room properly": "Registrar una sala a fondo",
  "Sections": "Secciones",
  "Session Log": "Diario de sesión",
  "Session scratchpad": "Bloc de la sesión",
  "Set level {0}": "Nivel {0}",
  "Set level {0}: Ability Score Improvement": "Nivel {0}: Mejora de puntuación de característica",
  "Set level {0}: Saboteur: Blastjumper": "Nivel {0}: Saboteur: Blastjumper",
  "Set level {0}: Saboteur: Bombardier, Saboteur: Hair Trigger": "Nivel {0}: Saboteur: Bombardier, Saboteur: Hair Trigger",
  "Set level {0}: Saboteur: Emergent Ordnance": "Nivel {0}: Saboteur: Emergent Ordnance",
  "Set level {0}: Saboteur: Mad Bomber": "Nivel {0}: Saboteur: Mad Bomber",
  "Share & save": "Compartir y guardar",
  "Shoes and posture. Anyone who's lived in the zone knows this one — consider giving it free.": "Zapatos y postura. Cualquiera que haya vivido en la zona lo sabe — plantéate darlo gratis.",
  "Show your DM.": "Enséñaselo a tu DM.",
  "Skill": "Habilidad",
  "Skill Proficiencies": "Competencia en habilidades",
  "Skills": "Habilidades",
  "Skills & proficiencies": "Habilidades y competencias",
  "Sleight of Hand": "Juego de Manos",
  "Sloppy amateur": "Aficionado torpe",
  "Someone is spending a resource.": "Alguien está gastando un recurso.",
  "Someone is watching the watchroom": "Alguien está vigilando la sala de vigilancia",
  "Something you do out of turn, when a trigger described by a feature happens. One per round.": "Algo que haces fuera de tu turno, cuando ocurre el desencadenante que describe un rasgo. Una por asalto.",
  "Speed": "Velocidad",
  "Spend each slot shown. If you're new, take the ability increase and put both points into your class's primary ability.": "Gasta cada hueco que aparece. Si empiezas, coge la mejora de característica y pon los dos puntos en la característica principal de tu clase.",
  "Spend your {0} points.": "Gasta tus {0} puntos.",
  "Splice a feed off a camera network": "Pinchar la señal de una red de cámaras",
  "Stabilise someone at {0} HP": "Estabilizar a alguien a {0} PG",
  "Stamp the time": "Marcar la hora",
  "Standard array": "Reparto estándar",
  "Standard array is the simplest: you get {0}, {1}, {2}, {3}, {4} and {5} to assign.": "El reparto estándar es lo más sencillo: tienes {0}, {1}, {2}, {3}, {4} y {5} para repartir.",
  "Standard array ★": "Reparto estándar ★",
  "Start from a template — it's faster than a blank form.": "Empieza con una plantilla — es más rápido que un formulario en blanco.",
  "Starting characters usually don't have millions of credits. Ask your DM what you can afford before you go shopping.": "Los personajes iniciales no suelen tener millones de créditos. Pregunta a tu DM qué te puedes permitir antes de ir de compras.",
  "Starting credits": "Créditos iniciales",
  "Starting level": "Nivel inicial",
  "Stealth": "Sigilo",
  "Step {0}": "Paso {0}",
  "Step {0} of {1}": "Paso {0} de {1}",
  "Str": "Fue",
  "Str (Athletics)": "Fue (Atletismo)",
  "Str/Con": "Fue/Con",
  "Str/Con saves": "salvaciones Fue/Con",
  "Str/Dex": "Fue/Des",
  "Str/Wis": "Fue/Sab",
  "Str/Wis saves": "salvaciones Fue/Sab",
  "Straight from the book — The Technomancer's Textbook, v{0}.{1} — Final.": "Directo del libro — The Technomancer's Textbook, v{0}.{1} — Final.",
  "Street Cred adds to Charisma checks — check the party's track before setting the DC.": "La Reputación callejera suma a las pruebas de Carisma — mira el marcador del grupo antes de fijar la CD.",
  "Strength": "Fuerza",
  "Strength save": "salvación de Fuerza",
  "Strength score": "puntuación de Fuerza",
  "Subclasses": "Subclases",
  "Subdermal and well-fitted": "Subdérmico y bien ajustado",
  "Success moves the price {0}-{1}%, not to whatever they wanted. A fixer's cut is not negotiable.": "El éxito mueve el precio un {0}-{1}%, no lo deja en lo que querían. La comisión de un fixer no se negocia.",
  "Survival": "Supervivencia",
  "Swap one skill for Technology": "Cambiar una habilidad por Tecnología",
  "Table": "Mesa",
  "Take": "Tomar",
  "Taken": "Tomada",
  "Talk someone out of violence": "Convencer a alguien de no usar la violencia",
  "Tearing ware loose does {0}d{1} to {2}d{3} slashing by grade — see the Tearing Ware Loose table. Doing it properly takes a clinic.": "Arrancar ware hace de {0}d{1} a {2}d{3} de daño cortante según el grado — mira la tabla Arrancar Ware. Hacerlo bien requiere una clínica.",
  "Technology": "Tecnología",
  "Technology replaces Arcana for anything with a circuit in it.": "Tecnología sustituye a Arcanos en todo lo que lleve un circuito dentro.",
  "Technology — the book's new skill": "Tecnología — la habilidad nueva del libro",
  "Tell a lie to someone's face": "Mentirle a alguien a la cara",
  "Tell them what the person's manner suggests, not a verdict. Insight reads people, not facts.": "Diles qué sugiere la actitud de esa persona, no un veredicto. Perspicacia lee a la gente, no los hechos.",
  "Tell whether someone is corporate": "Reconocer si alguien es de una corporación",
  "The Rogue archetype from the book. Features grey out until your character reaches the level that grants them.": "El arquetipo de Rogue del libro. Los rasgos salen en gris hasta que tu personaje alcanza el nivel que los otorga.",
  "The default. Most rolls live here.": "Lo normal. Aquí cae la mayoría de las tiradas.",
  "The defender may use Acrobatics instead. Their choice, not yours.": "Quien se defiende puede usar Acrobacias en su lugar. Lo elige él, no tú.",
  "The die you roll for health each level. A d{0} class is tougher than a d{1} class. This app adds the average for you.": "El dado que tiras para la salud en cada nivel. Una clase de d{0} aguanta más que una de d{1}. Esta aplicación suma la media por ti.",
  "The easiest to run at a table are Fighter, Barbarian and Chromehound — you mostly hit things and are hard to kill. Wirewalker and Puppeteer have the most moving parts.": "Las más fáciles de llevar en mesa son Fighter, Barbarian y Chromehound — sobre todo pegas cosas y eres difícil de matar. Wirewalker y Puppeteer son las que más piezas tienen.",
  "The god notices someone": "El dios se fija en alguien",
  "The main thing you do on your turn — attack, cast, run a program. One per turn.": "Lo principal que haces en tu turno — atacar, lanzar, ejecutar un programa. Una por turno.",
  "The number you actually add to dice rolls, worked out from an ability score. Score {0}–{1} gives +{2}, and every {3} points above or below shifts it by {4}. Score {5} gives +{6}.": "El número que sumas de verdad a las tiradas, calculado a partir de una puntuación de característica. Una puntuación de {0}–{1} da +{2}, y cada {3} puntos por encima o por debajo lo mueven {4}. Una puntuación de {5} da +{6}.",
  "The personality tables at the bottom are optional. Roll them if you want ideas for who this person actually is.": "Las tablas de personalidad del final son opcionales. Tíralas si quieres ideas sobre quién es esta persona en realidad.",
  "The picks bind. Another attempt takes ten minutes, or the tools break.": "Las ganzúas se atascan. Otro intento cuesta diez minutos, o se rompen las herramientas.",
  "The record is gone and the deletion is logged. Someone will read that log.": "El registro ya no está y el borrado queda anotado. Alguien leerá ese anotado.",
  "The roll at the start of a fight that decides turn order. It's a d{0} plus your Dexterity modifier.": "La tirada del principio de un combate que decide el orden de turnos. Es un d{0} más tu modificador de Destreza.",
  "The ruling desk works without them, but the useful half is seeing each character's real modifier next to the DC.": "La mesa de arbitraje funciona sin ellos, pero la mitad útil es ver el modificador real de cada personaje junto a la CD.",
  "The splice holds for one scene, then security notices the duplicate stream.": "El pinchazo aguanta una escena; después seguridad detecta el flujo duplicado.",
  "The table": "La mesa",
  "The “What you can do” list above is sorted that way on purpose — read it off the sheet, nobody memorises this.": "La lista «Lo que puedes hacer» de arriba está ordenada así a propósito — léela de la hoja, esto no lo memoriza nadie.",
  "There is no wrong answer. Nothing is locked in — you can change class right up until your first session.": "No hay respuesta equivocada. Nada queda fijado — puedes cambiar de clase hasta el momento de tu primera sesión.",
  "They don't attack. They also don't leave, and now they've seen your face.": "No atacan. Tampoco se van, y ya te han visto la cara.",
  "They don't call it. They just stop volunteering anything.": "No dan la alarma. Simplemente dejan de contar nada por su cuenta.",
  "They don't land — they drop a district. Work out where they come down before you work out the damage.": "No aterrizan — sueltan un distrito. Decide dónde caen antes de calcular el daño.",
  "They fall more than {0} feet": "Caen más de {0} pies",
  "They have a physical tap on the cable": "Tienen un pinchazo físico en el cable",
  "They have a stolen genuine one to copy": "Tienen uno auténtico robado del que copiar",
  "They have orders and a supervisor": "Tienen órdenes y un supervisor",
  "They install second-hand ware": "Se instalan ware de segunda mano",
  "They keep it on the road and lose the thing they were chasing.": "Mantienen el vehículo en la carretera y pierden lo que perseguían.",
  "They learn something true and out of date, and are remembered asking.": "Se enteran de algo cierto y desfasado, y se recuerda que preguntaron.",
  "They try to netrun on consecrated ground": "Intentan netrunear en suelo consagrado",
  "They turn on whoever is closest. That is usually the person who just saved them.": "Se vuelven contra quien tengan más cerca. Suele ser quien acaba de salvarles.",
  "They want to pay in favours rather than grams": "Quieren pagar en favores en vez de en gramos",
  "They'll tell you if anything needs changing for their game — starting level, how much money you begin with, whether Humanity is being used at all.": "Te dirán si hay que cambiar algo para su partida — nivel inicial, con cuánto dinero empiezas, o si se usa Humanidad siquiera.",
  "They're paid to be here and you're offering more": "Les pagan por estar aquí y tú ofreces más",
  "Things closing in. Fill a segment whenever the party spends time, makes noise, or gets unlucky.": "Las cosas se cierran. Rellena un segmento cada vez que el grupo gaste tiempo, haga ruido o tenga mala suerte.",
  "This book's tracker for how much of you is still a person. Every implant costs some. Run out and your character is lost.": "El medidor de este libro para saber cuánto queda de persona en ti. Cada implante cuesta algo. Si se agota, pierdes al personaje.",
  "This is everything you've chosen, worked out into the numbers you'll actually use at the table.": "Esto es todo lo que has elegido, convertido en los números que vas a usar de verdad en la mesa.",
  "This lists what the Technomancer's Textbook and your choices add. Rogue's core features — Sneak Attack, Rage, Spellcasting and the rest — come from the Player's Handbook and aren't reproduced here, so keep that to hand as well.": "Aquí aparece lo que añaden el Technomancer's Textbook y tus decisiones. Los rasgos básicos de Rogue — Ataque Furtivo, Furia, Lanzamiento de Conjuros y los demás — vienen del Manual del Jugador y no se reproducen aquí, así que tenlo también a mano.",
  "Tip": "Consejo",
  "Toggle beginner guide": "Mostrar u ocultar la guía para principiantes",
  "Toggle theme": "Cambiar tema",
  "Tone": "Tono",
  "Tool": "Herramienta",
  "Tool Proficiencies": "Competencia con herramientas",
  "Trace a signal back to its source": "Rastrear una señal hasta su origen",
  "Trivial {0}": "Trivial {0}",
  "Turn": "Turno",
  "Two portrait pages in the familiar D&D layout.": "Dos páginas verticales con la maquetación clásica de D&D.",
  "T{0} ·": "T{0} ·",
  "Unarmoured": "Sin armadura",
  "Use passive Perception unless they said they were looking. Don't ask for a roll you'd have made in secret.": "Usa la Percepción pasiva salvo que hayan dicho que estaban mirando. No pidas una tirada que habrías hecho en secreto.",
  "Use the guard's passive Perception unless they're actively searching. Don't roll for them twice.": "Usa la Percepción pasiva del guardia salvo que esté buscando activamente. No tires dos veces por él.",
  "Use these settings on my character": "Usar estos ajustes en mi personaje",
  "Visible chrome helps here and hurts on Persuasion. Below {0}% Humanity that's a real trade.": "El cromo visible ayuda aquí y perjudica en Persuasión. Por debajo del {0}% de Humanidad es un intercambio real.",
  "Warlock Invocations": "Invocaciones de brujo",
  "Watch the Humanity bar. Staying above {0}% keeps you free of any penalty.": "Vigila la barra de Humanidad. Por encima del {0}% no tienes ninguna penalización.",
  "Wet, sheer, or under fire": "Mojado, vertical o bajo fuego",
  "What does AC mean?": "¿Qué significa CA?",
  "What does Ability scores mean?": "¿Qué significan las puntuaciones de característica?",
  "What does ability score improvement mean?": "¿Qué significa mejora de puntuación de característica?",
  "What does action mean?": "¿Qué significa acción?",
  "What does archetype mean?": "¿Qué significa arquetipo?",
  "What does bonus action mean?": "¿Qué significa acción adicional?",
  "What does feat mean?": "¿Qué significa dote?",
  "What does health per level mean?": "¿Qué significa salud por nivel?",
  "What does hit points mean?": "¿Qué significan los puntos de golpe?",
  "What does humanity mean?": "¿Qué significa humanidad?",
  "What does initiative mean?": "¿Qué significa iniciativa?",
  "What does modifier mean?": "¿Qué significa modificador?",
  "What does money mean?": "¿Qué significa dinero?",
  "What does proficiency bonus mean?": "¿Qué significa bonificador de competencia?",
  "What does reaction mean?": "¿Qué significa reacción?",
  "What does saving throws mean?": "¿Qué significan las tiradas de salvación?",
  "What does skill mean?": "¿Qué significa habilidad?",
  "What does skills mean?": "¿Qué significan las habilidades?",
  "What does tier {0} mean?": "¿Qué significa nivel {0} de implante?",
  "What does {0} mean?": "¿Qué significa {0}?",
  "What to make them roll, what to set it at, and what each of them actually adds.": "Qué hacerles tirar, con qué dificultad y qué suma realmente cada uno.",
  "What you can do at level {0}": "Lo que puedes hacer en el nivel {0}",
  "When you level up, come back.": "Cuando subas de nivel, vuelve aquí.",
  "Wired Reflexes (Tier {0}) — {1},{2}₵": "Wired Reflexes (Nivel {0}) — {1},{2}₵",
  "Wired Reflexes T{0} ✕": "Wired Reflexes N{0} ✕",
  "Wis": "Sab",
  "Wis (Insight)": "Sab (Perspicacia)",
  "Wis (Medicine)": "Sab (Medicina)",
  "Wis (Perception)": "Sab (Percepción)",
  "Wis (Survival)": "Sab (Supervivencia)",
  "Wis/Cha": "Sab/Car",
  "Wis/Cha saves": "salvaciones Sab/Car",
  "Wisdom": "Sabiduría",
  "Wisdom save": "salvación de Sabiduría",
  "Wisdom score": "puntuación de Sabiduría",
  "Work out what's wrong with someone": "Averiguar qué le pasa a alguien",
  "You gain proficiency with the grenade launcher, rocket launcher, thumper, and demolitionist's tools.": "Ganas competencia con el lanzagranadas, el lanzacohetes, el thumper y las herramientas de demoliciones.",
  "You get a district, not an address — and they know they were traced.": "Consigues un distrito, no una dirección — y saben que les han rastreado.",
  "You mostly need a d{0}. The other dice come up for damage and healing.": "Casi siempre necesitas un d{0}. Los demás dados salen para daño y curación.",
  "You're done — what happens now": "Ya está — qué pasa ahora",
  "Your background is what you did for money before any of this started. It hands you": "Tu trasfondo es a qué te dedicabas antes de que empezara todo esto. Te da",
  "Your background is what you did for money before any of this started. It hands you [[skill|skills]], tools, starting gear and a special ability. Your origin is where you came from, and gives a small perk plus a story hook.": "Tu trasfondo es a qué te dedicabas antes de que empezara todo esto. Te da [[skill|habilidades]], herramientas, equipo inicial y una capacidad especial. Tu origen es de dónde vienes, y da una pequeña ventaja más un gancho narrativo.",
  "Your class is your character's job — what they're good at and what they reach for when things go wrong. It decides your": "Tu clase es el oficio de tu personaje — en qué es bueno y a qué recurre cuando algo sale mal. Decide tus",
  "Your class is your character's job — what they're good at and what they reach for when things go wrong. It decides your [[hit die|health per level]], which [[saving throw|saving throws]] you're trained in, and most of what you can do.": "Tu clase es el oficio de tu personaje — en qué es bueno y a qué recurre cuando algo sale mal. Decide tu [[hit die|salud por nivel]], en qué [[saving throw|tiradas de salvación]] tienes competencia y casi todo lo que puedes hacer.",
  "Your health. Damage takes them away; at {0} you fall unconscious and start making death saving throws.": "Tu salud. El daño te los quita; a {0} caes inconsciente y empiezas a hacer tiradas de salvación de muerte.",
  "[[ability score|Ability scores]] describe your body and mind. What matters at the table is the [[modifier]] underneath each one — that's what you add to your dice.": "Las [[ability score|puntuaciones de característica]] describen tu cuerpo y tu mente. Lo que importa en la mesa es el [[modifier|modificador]] que va debajo de cada una — eso es lo que sumas a tus dados.",
  "ability score": "puntuación de característica",
  "ability score improvement": "mejora de puntuación de característica",
  "action": "acción",
  "archetype": "arquetipo",
  "armour class": "clase de armadura",
  "bonus action": "acción adicional",
  "credits": "créditos",
  "describe your body and mind. What matters at the table is the": "describen tu cuerpo y tu mente. Lo que importa en la mesa es el",
  "d{0} +": "d{0} +",
  "d{0} hit die": "dado de golpe d{0}",
  "feat": "dote",
  "for paper, or": "para papel, o",
  "hack a door · talk them down · they fall · second-hand ware…": "hackear una puerta · calmarles · se caen · ware de segunda mano…",
  "health per level": "salud por nivel",
  "hit die": "dado de golpe",
  "hit points": "puntos de golpe",
  "humanity": "humanidad",
  "if something grants it, and your movement.": "si algo te la da, y tu movimiento.",
  "implants to start. They're cheap in both currencies.": "implantes para empezar. Son baratos en las dos monedas.",
  "in the dossier — and it becomes yours.": "en el dosier — y pasa a ser tuyo.",
  "initiative": "iniciativa",
  "instead. Some classes also learn new things as they level.": "en su lugar. Algunas clases además aprenden cosas nuevas al subir de nivel.",
  "is a specialisation inside your class. Two Rogues can play completely differently depending on which one they took.": "es una especialización dentro de tu clase. Dos Rogues pueden jugarse de forma totalmente distinta según cuál hayan cogido.",
  "is something you roll for outside combat. Being trained in one means adding your": "es algo que tiras fuera del combate. Tener competencia en una significa sumar tu",
  "modifier": "modificador",
  "money": "dinero",
  "no roll": "sin tirada",
  "not set": "sin elegir",
  "original material, not from the PDF": "material original, no viene del PDF",
  "p. {0}": "p. {0}",
  "proficiency bonus": "bonificador de competencia",
  "reaction": "reacción",
  "saving throw": "tirada de salvación",
  "saving throws": "tiradas de salvación",
  "skill": "habilidad",
  "skills": "habilidades",
  "tier": "nivel de implante",
  "to paste into Discord, Notion, a Google Doc or wherever your group keeps things.": "para pegarla en Discord, Notion, un documento de Google o donde vuestro grupo guarde las cosas.",
  "to that roll, which is a big deal.": "a esa tirada, que es mucho.",
  "underneath each one — that's what you add to your dice.": "debajo de cada uno — eso es lo que sumas a tus dados.",
  "unlocks at level {0}": "se desbloquea en el nivel {0}",
  "you're trained in, and most of what you can do.": "en las que tienes competencia, y casi todo lo que puedes hacer.",
  "{0} (+{1}) · save +{2}": "{0} (+{1}) · salv. +{2}",
  "{0} (+{1}) · save -{2}": "{0} (+{1}) · salv. -{2}",
  "{0} (-{1}) · save +{2}": "{0} (-{1}) · salv. +{2}",
  "{0} (-{1}) · save -{2}": "{0} (-{1}) · salv. -{2}",
  "{0} / {1} taken": "{0} / {1} tomadas",
  "{0} archetypes · choose at level {1}": "{0} arquetipos · se elige en el nivel {1}",
  "{0} classes from the book and {1} more from the Neon Ledger expansion, which bring a resource of their own. {2} archetypes between them.": "{0} clases del libro y {1} más de la expansión Neon Ledger, que traen un recurso propio. {2} arquetipos entre todas.",
  "{0} installed · {1},{2}₵": "{0} instalados · {1},{2}₵",
  "{0} items": "{0} objetos",
  "{0} level-up choice waiting — take an ability increase or a feat.": "{0} decisión de subida de nivel pendiente — coge una mejora de característica o una dote.",
  "{0} level-up choices waiting — take an ability increase or a feat.": "{0} decisiones de subida de nivel pendientes — coge una mejora de característica o una dote.",
  "{0}% · Baseline": "{0}% · Base",
  "{0}/{1} done": "{0}/{1} hechos",
  "· p. {0}": "· p. {0}",
  "·bg": "·bg",
  "— Rules are the SRD's, unchanged — same rolls, same numbers, same durations. Only the description around them is written for Cathedra, so a table using the printed book and a table using this site are playing the same game.": "— Las reglas son las del SRD, sin cambios: mismas tiradas, mismos números, mismas duraciones. Solo la descripción que las rodea está escrita para Cathedra, de modo que una mesa que use el libro impreso y otra que use esta web están jugando al mismo juego.",
  "— at level {0} you gain Ability Score Improvement.": "— en el nivel {0} obtienes una Mejora de puntuación de característica.",
  "— level {0}": "— nivel {0}",
  "← Back to Abilities": "← Volver a Características",
  "← Back to Archetype": "← Volver a Arquetipo",
  "← Back to Background": "← Volver a Trasfondo",
  "← Back to Chrome & Gear": "← Volver a Cromo y equipo",
  "← Back to Class": "← Volver a Clase",
  "← Back to Level-Ups": "← Volver a Subidas de nivel",
  "← Back to Proficiencies": "← Volver a Competencias",
  "Muscle": "Músculo",
  "Face": "Cara",
  "Tech": "Técnica",
  "Arcane": "Arcano",
  "Support": "Apoyo",
  "Specialist Crew": "Cuadrilla especialista",
  "Built for one kind of job. Anything outside that lane costs them.": "Hecha para un tipo de trabajo. Todo lo que se salga de ese carril les cuesta.",
  "Balanced Crew": "Cuadrilla equilibrada",
  "Solid coverage, one soft spot at most.": "Buena cobertura, un punto débil como mucho.",
  "Full Spectrum Crew": "Cuadrilla de espectro completo",
  "Nothing left to a coin flip.": "Nada queda a cara o cruz.",
  "Two scouts who call the opening move together.": "Dos exploradores que deciden juntos el primer movimiento.",
  "+1 initiative to both, applied automatically.": "+1 a la iniciativa de ambos, aplicado automáticamente.",
  "Two front-liners holding the same door. Be generous about cover when they stand together.": "Dos de primera línea defendiendo la misma puerta. Sé generoso con la cobertura cuando estén juntos.",
  "Faith and law recognise their own. Institutions vouch for this pair, or shelter them.": "La fe y la ley reconocen a los suyos. Las instituciones responden por esta pareja, o los acogen.",
  "A hype-man and a wrecking ball. The crowd remembers the show, not the damage.": "Un animador y una bola de demolición. El público recuerda el espectáculo, no los destrozos.",
  "The physical break-in and the digital one happen the same night. Alarms built for one miss the other.": "El asalto físico y el digital ocurren la misma noche. Las alarmas hechas para uno se pierden el otro.",
  "The Streetdoc keeps the chrome running past what the flesh under it should survive. Downtime recovery goes faster for both.": "El Streetdoc mantiene el cromo funcionando más allá de lo que debería sobrevivir la carne que hay debajo. La recuperación entre trabajos va más rápida para los dos.",
  "One knows who to talk to. The other makes them want to listen. A job neither lands alone.": "Uno sabe con quién hablar. El otro hace que quieran escuchar. Un trabajo que ninguno consigue por su cuenta.",
  "The Cleric already talks to what used to be human. The Bioforged, still becoming something else, finds that more comforting than most patients do.": "El Cleric ya habla con lo que antes fue humano. El Bioforged, que todavía se está convirtiendo en otra cosa, lo encuentra más reconfortante que la mayoría de los pacientes.",
  "A drone that can also lie for a living. Crowd control and misdirection, layered.": "Un dron que además se gana la vida mintiendo. Control de masas y distracción, por capas.",
  "Someone who has died before, and someone who plans not to. Close calls read like a checklist.": "Alguien que ya ha muerto antes y alguien que piensa no hacerlo. Las situaciones al límite se leen como una lista de comprobación.",
  "Whichever companion the job needed this week — gears or claws — one of these two brought it.": "El compañero que hiciera falta esta semana —engranajes o garras—, uno de estos dos lo trajo.",
  "Two front-liners who have fought beside each other before swing like they know where the other's blow is going.": "Dos de primera línea que ya han combatido juntos golpean como si supieran adónde va el golpe del otro.",
  "A patron's secrets and a fixer's contacts. Very little in the city stays hidden from these two.": "Los secretos de un patrón y los contactos de un fixer. Muy poco en la ciudad se les queda oculto a estos dos.",
  "Chrome breaks, and the Artificer understands why. Cyberware repairs cost half the usual downtime with both present.": "El cromo se rompe, y el Artificer entiende por qué. Las reparaciones de ciberware cuestan la mitad del tiempo habitual con los dos presentes.",
  "A body that grows what it needs, a mind that has stopped needing a body at all. Damage that should slow either one down mostly doesn't.": "Un cuerpo que hace crecer lo que necesita, una mente que ha dejado de necesitar cuerpo alguno. El daño que debería frenar a cualquiera de los dos casi nunca lo hace.",
  "Two very different congregations. Both of them do what these two ask.": "Dos congregaciones muy distintas. Las dos hacen lo que estos dos piden.",
  "Arcane theory and network theory rhyme. Warded doors, locked ports — one of these two has seen the trick before.": "La teoría arcana y la teoría de redes riman. Puertas protegidas, puertos cerrados: uno de estos dos ya ha visto el truco.",
  "Raw power and remote hands. Neither has to explain what the other needed done.": "Poder en bruto y manos a distancia. Ninguno tiene que explicar lo que el otro necesitaba que se hiciera.",
  "You get searched at the door.": "Te cachean en la puerta.",
  "No one owes them the truth.": "Nadie les debe la verdad.",
  "Nobody is afraid of them, and nobody comes running.": "Nadie les tiene miedo, y nadie viene corriendo.",
  "A fixer will take your call.": "Un fixer te coge el teléfono.",
  "Rumours are starting, and most of them are accurate.": "Empiezan a correr rumores, y la mayoría son ciertos.",
  "Low muscle might hesitate half a beat.": "Los matones de poca monta pueden dudar medio segundo.",
  "A minor favour once per job, without spending a Favour die.": "Un favor menor una vez por trabajo, sin gastar un dado de Favor.",
  "A contact points them the right way once, unasked.": "Un contacto les señala el camino una vez, sin que se lo pidan.",
  "A rival crew might skip a fight it doesn't need.": "Una cuadrilla rival puede saltarse una pelea que no necesita.",
  "Doors open. So do files — corps run their faces on sight.": "Se abren puertas. También expedientes: las corporaciones les pasan la cara por el sistema en cuanto los ven.",
  "Strangers volunteer what they know before being asked.": "Los desconocidos cuentan lo que saben antes de que se lo pregunten.",
  "Hostile reactions get rare, and someone is probably filming.": "Las reacciones hostiles escasean, y probablemente alguien esté grabando.",
  "Rivals inherit their enemies. One faction actively wants them dead.": "Los rivales heredan sus enemigos. Una facción los quiere muertos activamente.",
  "People assume they already know, and talk carefully.": "La gente da por hecho que ya lo saben, y habla con cuidado.",
  "A weaker force refuses the fight outright. A desperate one ambushes instead.": "Una fuerza más débil rechaza la pelea sin más. Una desesperada tiende una emboscada en su lugar.",
  "Strangers do favours unasked, and the price on their heads funds a small army.": "Los desconocidos les hacen favores sin que se los pidan, y el precio por sus cabezas financia un pequeño ejército.",
  "Nobody bothers lying to a myth. It has never once worked.": "Nadie se molesta en mentirle a un mito. No ha funcionado ni una sola vez.",
  "Reactions skew to the ends: someone dies for them, or someone is paid enough to try the other thing.": "Las reacciones se van a los extremos: alguien muere por ellos, o a alguien le pagan lo bastante para intentar lo contrario.",
  "Hostile": "Hostil",
  "They move against the party — draw down, call it in, shut the door.": "Actúan contra el grupo: desenfundan, dan el aviso, cierran la puerta.",
  "Wary": "Receloso",
  "Grudging and minimal. One question answered, help only under duress, and they take the safe side of a fight.": "A regañadientes y lo mínimo. Una pregunta respondida, ayuda solo bajo presión, y en una pelea se ponen del lado seguro.",
  "Neutral": "Neutral",
  "Business as usual. Deals fairly, takes no side unless pushed.": "Negocio como siempre. Trata con justicia y no toma partido salvo que lo empujen.",
  "Friendly": "Cordial",
  "Leans their way — a tip, a discount, a shout of warning, a moment's hesitation before swinging.": "Se inclina de su lado: un soplo, un descuento, un grito de aviso, un instante de duda antes de golpear.",
  "Ally": "Aliado",
  "Steps in. Cover fire, a rescue, a lie told on the party's behalf. This is the roll that turns a fight.": "Interviene. Fuego de cobertura, un rescate, una mentira dicha en nombre del grupo. Esta es la tirada que da la vuelta a una pelea.",
  "Standing together": "Lo que son juntos",
  "No named pair at this table. That is not a penalty — it means whatever they pull off is theirs.": "No hay ninguna pareja con nombre en esta mesa. No es un penalizador: significa que lo que consigan es suyo.",
  "Yours to move. A point for a job the street saw, one back for folding in public.": "Tuya para moverla. Un punto por un trabajo que la calle vio, uno menos por achantarse en público.",
  "Looking into things": "Al indagar",
  "When it turns ugly": "Cuando se pone feo",
  "NPC reaction": "Reacción de PNJ",
  "How someone takes them, given who they are. Roll it before a fight starts, in the middle of one, or at a door.": "Cómo se los toma alguien, dado quiénes son. Tírala antes de que empiece una pelea, en mitad de una, o en una puerta.",
  "Situation": "Situación",
  "Straight": "Normal",
  "Advantage": "Ventaja",
  "Roll the reaction": "Tira la reacción",
  "Reaction check": "Prueba de reacción",
  "{0}% chance of Friendly or better": "{0}% de probabilidad de Cordial o mejor",
  "Cred {0}": "Reputación {0}",
  "Cred {0}, situation {1}": "Reputación {0}, situación {1}",
  "+{0} to Charisma checks": "+{0} a las pruebas de Carisma",
  "Ambush Team +1": "Ambush Team +1",
  "Roll the god's attention": "Tira la atención del dios",
  "d{0} at the start of the session. On a {1} the god notices one character.": "d{0} al inicio de la sesión. Con un {1} el dios se fija en un personaje.",
  "Who's best at…": "Quién es mejor en…",
  "Roll it secretly for everyone": "Tírala en secreto por todos",
  "On a failure": "Si falla",
  "snapshot taken {0}/{1}/{2} · re-paste their link after they level": "instantánea tomada el {0}/{1}/{2} · vuelve a pegar su enlace cuando suban de nivel",
  "Blacklisted": "En la lista negra",
  "The city has decided. Nothing legitimate is on offer at any price.": "La ciudad ya ha decidido. No hay nada legal en oferta a ningún precio.",
  "Every question is a warning to whoever they asked about.": "Cada pregunta es un aviso para aquel por quien preguntaron.",
  "There is a standing rate for them, and more than one person knows it.": "Hay una tarifa fija por sus cabezas, y más de uno se la sabe.",
  "Poison": "Veneno",
  "Being seen with them costs other people work, and those people know it.": "Que te vean con ellos le cuesta trabajo a los demás, y los demás lo saben.",
  "Doors that were open close as they reach them.": "Las puertas que estaban abiertas se cierran justo cuando llegan.",
  "A fight they start is one the neighbourhood finishes, on the other side.": "Una pelea que empiezan la termina el barrio, y del otro lado.",
  "Marked": "Señalados",
  "Fixers stop returning calls. The work that reaches them is the work nobody else took.": "Los fixers dejan de devolver las llamadas. El trabajo que les llega es el que nadie más quiso.",
  "Ask twice about the same thing and it gets back to the wrong person.": "Pregunta dos veces por lo mismo y llega a oídos de quien no debe.",
  "Somebody is already being paid to be there when it starts.": "A alguien ya le están pagando por estar allí cuando empiece.",
  "Bad paper": "Papel mojado",
  "Their name on a job makes people quote higher. Some stop quoting.": "Su nombre en un trabajo hace que la gente cobre más. Algunos dejan de dar presupuesto.",
  "The easy sources dry up, and they pay for what they used to be told.": "Las fuentes fáciles se secan, y pagan por lo que antes les contaban.",
  "Nobody steps in on their side. They have seen how that ends.": "Nadie interviene de su lado. Ya han visto cómo acaba eso.",
  "Burned": "Quemados",
  "Somebody is telling the story of how they did not pay, and it is mostly true.": "Alguien anda contando cómo no pagaron, y es cierto casi todo.",
  "People answer, then check who else was listening.": "La gente responde y luego mira quién más estaba escuchando.",
  "A crew that would have walked past decides to watch them instead.": "Una cuadrilla que habría pasado de largo decide quedarse a mirarlos.",
  "Synergies": "Sinergias",
  "Pairs with": "Hace pareja con",
  "-{0} to Charisma checks": "-{0} a las pruebas de Carisma",
  "−{0} HUM": "−{0} HUM"
};

/* Patterns, for text the application builds from the data. Enumerating every
   "Add <gear>" button would go stale the moment a gear item is added, and the
   thing being named is a proper noun that stays English anyway. {*} matches a
   run and is passed straight through. Tried only after an exact match fails. */
window.TTES.patterns = [
  ["Still to do here: {*}", "Aquí queda por hacer: {*}"],
  ["Go to {*}", "Ir a {*}"],
  ["Next: {*} →", "Siguiente: {*} →"],
  ["← Back to {*}", "← Volver a {*}"],
  ["Say: “Roll {*}.”", "Di: «Tira {*}»."],
  ["— at level {*} you gain {*}.", "— en el nivel {*} obtienes {*}."],
  ["Prereq: {*}", "Requisito: {*}"],
  ["Feature: {*}", "Rasgo: {*}"],
  ["Background · {*}", "Trasfondo · {*}"],
  ["Add {*}", "Añadir {*}"],
  ["{*} · level {*}", "{*} · nivel {*}"],
  ["{*} · lv {*}", "{*} · niv {*}"],
  ["{*} · CR {*}", "{*} · VD {*}"],
  ["{*} vs {*}", "{*} contra {*}"],
  ["with {*}", "con {*}"],
  ["Level {*}", "Nivel {*}"],
  ["{*}  (their passive {*} {*})", "{*}  ({*} pasiva {*})"]
];
