/* npcs.js: NPCs that level with the table. GM only, read by gm.js.
 *
 * Every NPC here is built for one number, the table's NPC level (1 to 20, the
 * slider on the NPCs screen, which starts at the party's average level). The
 * same Corpo Security guard is a fair fight at level 3 and at level 12:
 * gm.js's npcBuild() works out its scores, hit points, armour, attack bonus,
 * weapon, number of attacks, save DCs and which of its features it has,
 * from its role and the level.
 *
 * roles   how tough and how dangerous, the same for every NPC of that role:
 *   die     hit die size;  hd  hit dice per level (a boss has more than a mook)
 *   ac      base armour class (+1 at levels 7, 13 and 19)
 *   atks    [from level, attacks per turn] (Multiattack)
 *   dmgPb   adds the proficiency bonus to weapon damage (bosses hit harder)
 *   xp      false: worth nothing on the difficulty meter (bystanders)
 *   kind    "mook" draws the one-line card
 *   Challenge rating isn't set here: gm.js works it out from the statblock
 *   it builds, so the difficulty meter weighs what the NPC actually does.
 *
 * kits    weapons that get better as the level rises: four tiers, for levels
 *         1-4, 5-10, 11-16 and 17-20, each a name and a damage die.
 *         abil "best" uses the better of Str and Dex (finesse).
 *
 * archetypes
 *   id, name, cat (a category id), role, desc
 *   scores  at level 1; the prime ability rises by 2 at levels 4, 8, 12,
 *           16 and 19 until it reaches 20, then Con does
 *   prime   the ability its attacks use (weapons with their own abil aside)
 *   dcAbil  the ability its save DCs use (default: prime)
 *   saves, skills   proficient ones
 *   kits    weapon kit ids
 *   powers  [{ name, min, dice?: [4 tiers], aoe?, text }] actions that
 *           aren't weapon attacks. Their damage adds the modifier of the
 *           ability behind the save DC; aoe marks one that hits an area
 *           (it counts double when the challenge rating is worked out);
 *           heal marks one that restores hit points instead.
 *   traits, reactions  [{ name, min, text }]
 *   In any text: {dc} the save DC, {pb} proficiency bonus, {dmg} the power's
 *   dice at this level. A feature with min above the level isn't there yet.
 *   acFrom  [4 tiers] or a string; acAdj, init  small nudges
 *
 * The old fixed templates' names are all here (Corpo Security, Gutter
 * Ganger, Choir Fragment, and the rest): the story, the demo table and the
 * street encounters ask for NPCs by those names.
 */
window.TTNPC = {
  categories: [
    { id: "street", name: "Street", blurb: "Gangers, runners and the chrome-sick: the Gullet after dark." },
    { id: "religious", name: "Religious", blurb: "Reliquary clergy, pilgrims, and the Hush in the pipes." },
    { id: "house", name: "Corporate & Houses", blurb: "The four Houses' security, collectors and knights." },
    { id: "law", name: "Law & the Watch", blurb: "House Vigil: the Watch, the wards and the lifts." },
    { id: "tech", name: "Tech & machines", blurb: "Drones, turrets, netrunners and repossession rigs." },
    { id: "underworld", name: "Underworld", blurb: "Fixers, fences, smugglers and the people they hire." },
    { id: "medical", name: "Medical", blurb: "Ripperdocs, bone-carvers and the black clinics." },
    { id: "workers", name: "Workers & civilians", blurb: "The people the city runs on, and the crowds they make." },
    { id: "godtouched", name: "God-touched", blurb: "What grows in a god that won't finish dying." }
  ],

  roles: {
    bystander:  { name: "Bystander",  die: 6,  hd: 0.35, ac: 10, atks: [[1, 1]],                   xp: false, kind: "mook" },
    minion:     { name: "Minion",     die: 6,  hd: 0.75, ac: 12, atks: [[1, 1]],                   kind: "mook" },
    skirmisher: { name: "Skirmisher", die: 8,  hd: 1.15, ac: 14, atks: [[1, 1], [5, 2]] },
    soldier:    { name: "Soldier",    die: 8,  hd: 1.25, ac: 15, atks: [[1, 1], [5, 2], [11, 3]] },
    brute:      { name: "Brute",      die: 10, hd: 1.5,  ac: 13, atks: [[1, 1], [5, 2], [11, 3]] },
    controller: { name: "Controller", die: 8,  hd: 1.2,  ac: 12, atks: [[1, 1], [11, 2]] },
    support:    { name: "Support",    die: 8,  hd: 1.1,  ac: 12, atks: [[1, 1]] },
    elite:      { name: "Elite",      die: 10, hd: 1.75, ac: 16, atks: [[1, 2], [8, 3], [15, 4]] },
    boss:       { name: "Boss",       die: 12, hd: 2.5,  ac: 16, atks: [[1, 2], [6, 3], [13, 4]],  dmgPb: true }
  },

  // what every NPC of a role gains as it levels, on top of its own features
  roleTraits: {
    elite: [{ name: "Hard to pin", min: 9, text: "Advantage on saves against being stunned, paralysed or knocked prone." }],
    boss: [
      { name: "Boss", min: 1, text: "Takes one extra reaction each round, and its turn can't be skipped by a condition for more than one round." },
      { name: "Legendary resistance", min: 9, text: "Once a day, when it fails a saving throw, it can succeed instead." },
      { name: "Legendary resistance, again", min: 15, text: "It can use Legendary resistance twice a day." }
    ],
    minion: [{ name: "Mob", min: 5, text: "Advantage on attacks against a creature that two or more of its allies are next to." }]
  },

  kits: {
    unarmed:  { abil: "Str", dtype: "bludgeoning", range: "Melee, reach 5 ft.",
                names: ["Fists", "Fists", "Fists", "Fists"], dice: ["1d4", "1d4", "1d6", "1d6"] },
    knife:    { abil: "best", dtype: "slashing", range: "Melee, reach 5 ft., or thrown 20/60",
                names: ["Shiv", "Combat knife", "Mono-knife", "Mono-knife"], dice: ["1d4", "1d6", "2d6", "3d6"] },
    club:     { abil: "Str", dtype: "bludgeoning", range: "Melee, reach 5 ft.",
                names: ["Lead pipe", "Shock baton", "Shock maul", "Arc maul"], dice: ["1d6", "1d8", "2d8", "3d8"],
                note: "The shock versions: on a hit, Con save DC {dc} or no reactions until its next turn." },
    blade:    { abil: "best", dtype: "slashing", range: "Melee, reach 5 ft.",
                names: ["Machete", "Katana", "Monoblade", "Thermal katana"], dice: ["1d8", "2d6", "2d8", "3d8"] },
    heavy:    { abil: "Str", dtype: "bludgeoning", range: "Melee, reach 5 ft.",
                names: ["Sledge", "Reliquary maul", "Bone-breaker", "Thunder maul"], dice: ["1d10", "2d8", "3d8", "4d8"] },
    claws:    { abil: "best", dtype: "slashing", range: "Melee, reach 5 ft.",
                names: ["Cyberclaws", "Cyberclaws", "Mantis blades", "Mantis blades"], dice: ["1d6", "1d8", "2d8", "3d8"] },
    chromefist: { abil: "Str", dtype: "bludgeoning", range: "Melee, reach 5 ft.",
                names: ["Chrome fist", "Chrome fist", "Hydraulic fist", "Titan fist"], dice: ["1d8", "2d8", "3d8", "4d10"],
                note: "On a hit, the target is pushed 10 ft. if it's no bigger than Large." },
    pipeknife: { abil: "Dex", dtype: "piercing", range: "Melee, reach 5 ft.",
                names: ["Pipe-knife", "Pipe-knife", "Tuned pipe-knife", "Choir needle"], dice: ["1d6", "2d4", "2d6", "3d6"],
                note: "Silent. Nothing within 30 ft. hears the blow." },
    censer:   { abil: "Str", dtype: "fire", range: "Melee, reach 10 ft.",
                names: ["Censer chain", "Censer chain", "Burning censer", "Burning censer"], dice: ["1d6", "1d8", "2d8", "3d8"] },
    drill:    { abil: "Str", dtype: "piercing", range: "Melee, reach 5 ft.",
                names: ["Hand drill", "Marrow drill", "Rotary drill", "Core drill"], dice: ["1d8", "2d6", "2d10", "3d10"],
                note: "Ignores resistance to piercing damage." },
    bone:     { abil: "Str", dtype: "piercing", range: "Melee, reach 10 ft.",
                names: ["Bone spur", "Bone spur", "Marrow lance", "Marrow lance"], dice: ["1d8", "2d8", "3d8", "4d8"] },
    pistol:   { abil: "Dex", dtype: "piercing", range: "Ranged 50/150",
                names: ["Cheap pistol", "Heavy pistol", "Smart pistol", "Rail pistol"], dice: ["1d8", "2d6", "2d8", "3d8"],
                ammo: [8, 8, 10, 6] },
    smg:      { abil: "Dex", dtype: "piercing", range: "Ranged 40/120, burst fire",
                names: ["Machine pistol", "SMG", "Smart SMG", "Flechette SMG"], dice: ["2d4", "2d6", "2d8", "3d8"],
                ammo: [10, 30, 30, 40], note: "Burst: 10-ft. cube, Dex save DC {dc} or take the damage, 10 rounds." },
    rifle:    { abil: "Dex", dtype: "piercing", range: "Ranged 100/400",
                names: ["Hunting rifle", "Assault rifle", "Smart rifle", "Rail rifle"], dice: ["1d10", "2d8", "3d8", "4d8"],
                ammo: [5, 30, 30, 10] },
    shotgun:  { abil: "Dex", dtype: "piercing", range: "Ranged 15/40",
                names: ["Sawn-off", "Combat shotgun", "Auto-shotgun", "Dragon's-breath shotgun"], dice: ["2d4", "2d8", "3d8", "4d8"],
                ammo: [2, 6, 12, 12], note: "Within 15 ft., the target is also pushed 5 ft." },
    sniper:   { abil: "Dex", dtype: "piercing", range: "Ranged 200/800, heavy",
                names: ["Scoped rifle", "Sniper rifle", "Smart sniper", "Railgun"], dice: ["1d12", "4d4", "4d6", "5d8"],
                ammo: [5, 8, 8, 4] },
    slug:     { abil: "Dex", dtype: "piercing", range: "Ranged 60/180",
                names: ["Slug gun", "Slug gun", "Autocannon", "Autocannon"], dice: ["1d8", "2d6", "3d8", "4d8"] },
    dart:     { abil: "Dex", dtype: "poison", range: "Ranged 30/90",
                names: ["Dart gun", "Dart gun", "Needler", "Needler"], dice: ["1d4", "1d6", "2d6", "3d6"],
                note: "On a hit, Con save DC {dc} or poisoned until the end of its next turn." }
  },

  archetypes: [
    /* ============================== street ============================== */
    { id: "gutter-ganger", name: "Gutter Ganger", cat: "street", role: "minion",
      desc: "Undercity muscle for hire by the hour. Brave in a pack, gone when it thins.",
      scores: { Str: 11, Dex: 12, Con: 11, Int: 9, Wis: 9, Cha: 9 }, prime: "Dex",
      kits: ["knife", "pistol"], acFrom: "Scraps and a jacket",
      traits: [{ name: "Knows a way out", min: 1, text: "When half its crew is down, it runs; it always knows the nearest exit." }] },
    { id: "rib-runner", name: "Rib-runner", cat: "street", role: "skirmisher",
      desc: "Grew up jumping between ribs. Never where you aimed.",
      scores: { Str: 10, Dex: 16, Con: 12, Int: 10, Wis: 12, Cha: 10 }, prime: "Dex",
      skills: ["Acrobatics", "Athletics", "Stealth"], kits: ["knife", "pistol"], acFrom: "Light weave",
      traits: [{ name: "Wall-runner", min: 1, text: "Climbing costs no extra movement, and it takes no damage from falls of 30 ft. or less." },
               { name: "Hit and gone", min: 5, text: "After it attacks, it can Disengage as a bonus action." },
               { name: "Long jump", min: 11, text: "It can jump the gap between two ribs (60 ft.) with a running start." }] },
    { id: "chrome-junkie", name: "Chrome Junkie", cat: "street", role: "brute",
      desc: "More implant than person, and none of it fitted by anyone with a licence.",
      scores: { Str: 16, Dex: 10, Con: 15, Int: 7, Wis: 8, Cha: 7 }, prime: "Str",
      kits: ["chromefist"], acFrom: "Bolted plating", resist: "",
      traits: [{ name: "Twitching", min: 1, text: "Disadvantage on Wisdom saves; advantage on Strength checks." },
               { name: "Overclock", min: 5, text: "Once per fight, it takes an extra action on its turn, then takes {dmg} damage from its own chrome.",
                 dice: ["1d6", "2d6", "3d6", "4d6"] },
               { name: "Something else is driving", min: 11, text: "Immune to being frightened and charmed." }] },
    { id: "gang-boss", name: "Gang Boss", cat: "street", role: "elite",
      desc: "Runs three blocks of the Gullet and a ledger of who owes what.",
      scores: { Str: 14, Dex: 14, Con: 14, Int: 12, Wis: 12, Cha: 15 }, prime: "Dex", dcAbil: "Cha",
      saves: ["Dex", "Cha"], skills: ["Intimidation", "Insight"], kits: ["blade", "shotgun"], acFrom: "Armoured longcoat",
      powers: [{ name: "Get them!", min: 1, text: "Bonus action: up to three allies who can hear it move half their speed and make one attack each." }],
      reactions: [{ name: "Meat shield", min: 5, text: "When hit by an attack, it swaps places with an adjacent ally, who takes the hit." }] },
    { id: "street-samurai", name: "Street Samurai", cat: "street", role: "elite",
      desc: "A professional. Wired reflexes, a blade and a price.",
      scores: { Str: 16, Dex: 16, Con: 14, Int: 10, Wis: 12, Cha: 10 }, prime: "Dex",
      saves: ["Str", "Dex"], skills: ["Athletics", "Perception"], kits: ["blade", "pistol"], init: 2, acFrom: "Subdermal plate",
      traits: [{ name: "Wired reflexes", min: 1, text: "Advantage on initiative. On the first round it takes one extra action." },
               { name: "Pain editor", min: 5, text: "Resistance to bludgeoning, piercing and slashing damage while below half its hit points." }],
      reactions: [{ name: "Deflect", min: 8, text: "Adds {pb} to its AC against one melee attack it can see." }] },
    { id: "cyberpsycho", name: "Cyberpsycho", cat: "street", role: "boss",
      desc: "Someone who kept buying until nobody was left inside. Everyone runs.",
      scores: { Str: 18, Dex: 14, Con: 16, Int: 6, Wis: 8, Cha: 5 }, prime: "Str",
      saves: ["Str", "Con"], kits: ["claws", "smg"], acFrom: "What's left of the skin",
      immune: "psychic", condImmune: "charmed, frightened", senses: "darkvision 60 ft.",
      powers: [{ name: "Overload", min: 1, aoe: true, dice: ["2d6", "4d6", "6d6", "8d6"], text: "Recharge 5-6. 10-ft. burst of lightning around it: Dex save DC {dc}, {dmg} damage, half on a success." }],
      traits: [{ name: "Nothing left", min: 1, text: "The first time it drops to 0 HP, it drops to 1 instead." },
               { name: "Was someone", min: 1, text: "Anyone who knew them has disadvantage on attacks against them for the first round." },
               { name: "Frenzy", min: 9, text: "Advantage on all melee attacks while below half its hit points." }] },

    /* ============================== religious ============================== */
    { id: "reliquary-acolyte", name: "Reliquary Acolyte", cat: "religious", role: "minion",
      desc: "Candle-trimmer, door-watcher, singer to a door three floors down.",
      scores: { Str: 10, Dex: 10, Con: 10, Int: 10, Wis: 13, Cha: 11 }, prime: "Wis",
      skills: ["Religion"], kits: ["club"], acFrom: "Vestments",
      traits: [{ name: "Raise the bell", min: 1, text: "Its first action in a fight is to ring for help; 1d4 more acolytes arrive in 2 rounds." }] },
    { id: "pilgrim-zealot", name: "Pilgrim Zealot", cat: "religious", role: "brute",
      desc: "Climbed the Spine on their knees and will not be stopped on the stairs.",
      scores: { Str: 15, Dex: 10, Con: 16, Int: 8, Wis: 12, Cha: 12 }, prime: "Str",
      kits: ["censer"], acFrom: "Pilgrim's mask and chain",
      traits: [{ name: "Faith like a wall", min: 1, text: "Advantage on saves against being frightened or charmed." },
               { name: "Martyr", min: 5, text: "When it drops to 0 HP, every ally within 30 ft. gains {pb} temporary hit points." }] },
    { id: "hush-quieter", name: "Hush Quieter", cat: "religious", role: "skirmisher",
      desc: "Polite, young, sings beautifully. Says sorry before, and after.",
      scores: { Str: 10, Dex: 16, Con: 12, Int: 12, Wis: 14, Cha: 14 }, prime: "Dex", dcAbil: "Cha",
      skills: ["Stealth", "Performance", "Insight"], kits: ["pipeknife"], acFrom: "Grey tender's coat",
      powers: [{ name: "Quieting note", min: 1, text: "One creature within 30 ft. that can hear it: Wis save DC {dc} or fall asleep for 1 minute. It wakes if it takes damage or is shaken. Sleepers have disadvantage." },
               { name: "The lock forgets", min: 5, text: "It sings one note at a lock within 30 ft., which opens. Wards count as locks." }],
      traits: [{ name: "Through the pipes", min: 3, text: "It can hear anything said within 10 ft. of any tap or pipe in the building." },
               { name: "Restraint", min: 1, text: "It never harms anyone who hasn't seen the future. Everyone else, it steps around." }] },
    { id: "choir-tender", name: "Choir Tender", cat: "religious", role: "support",
      desc: "Keeps the Cantor's voices tuned, and its own voice steady.",
      scores: { Str: 9, Dex: 11, Con: 12, Int: 13, Wis: 15, Cha: 14 }, prime: "Wis",
      skills: ["Religion", "Medicine", "Performance"], kits: ["club"], acFrom: "Choir robes",
      powers: [{ name: "Harmony", min: 1, heal: true, dice: ["1d8", "2d8", "3d8", "4d8"], text: "Bonus action: one ally within 30 ft. regains {dmg} hit points." },
               { name: "Discord", min: 5, dice: ["2d6", "3d6", "4d6", "6d6"], text: "One creature within 60 ft.: Con save DC {dc} or {dmg} thunder damage and deafened until the end of its next turn." }] },
    { id: "reliquary-confessor", name: "Reliquary Confessor", cat: "religious", role: "controller",
      desc: "Hears confessions and sells indulgences. Remembers both.",
      scores: { Str: 9, Dex: 12, Con: 12, Int: 14, Wis: 16, Cha: 14 }, prime: "Wis",
      saves: ["Wis", "Cha"], skills: ["Insight", "Religion", "Persuasion"], kits: ["dart"], acFrom: "Blessed vestments",
      powers: [{ name: "Name your sin", min: 1, text: "One creature within 60 ft.: Wis save DC {dc} or it can't take reactions and has disadvantage on its next attack roll." },
               { name: "Repossession", min: 5, dice: ["2d8", "3d8", "4d8", "5d8"], text: "One creature with a rented Humanity buffer or chrome within 60 ft.: Con save DC {dc} or {dmg} psychic damage as the Reliquary takes its due." },
               { name: "Sanctuary", min: 11, text: "Consecrated ground within 30 ft. of it: enemies' powered chrome stops working entirely, not just at disadvantage." }] },
    { id: "hush-choirmaster", name: "Hush Choirmaster", cat: "religious", role: "boss",
      desc: "Hasn't slept a full night in fifty years, because someone has to be singing.",
      scores: { Str: 8, Dex: 12, Con: 14, Int: 16, Wis: 18, Cha: 18 }, prime: "Wis", dcAbil: "Cha",
      saves: ["Wis", "Cha", "Con"], skills: ["Insight", "Performance", "Religion"], kits: ["pipeknife"], acFrom: "Brass voice-box and robes",
      powers: [{ name: "Lullaby", min: 1, text: "Every enemy within 30 ft. that can hear it: Wis save DC {dc} or fall asleep for 1 minute. Seers have disadvantage." },
               { name: "Chord", min: 5, aoe: true, dice: ["2d8", "4d8", "6d8", "8d8"], text: "20-ft. radius: Con save DC {dc}, {dmg} thunder damage, half on a success." }],
      traits: [{ name: "The pipes answer", min: 1, text: "At the start of each round, water in any pipe within 60 ft. sings: one enemy of its choice has disadvantage on its next check." }] },

    /* ============================== corporate & houses ============================== */
    { id: "corpo-security", name: "Corpo Security", cat: "house", role: "soldier",
      desc: "House security: decent training, a contract and a radio.",
      scores: { Str: 14, Dex: 14, Con: 14, Int: 10, Wis: 12, Cha: 10 }, prime: "Dex",
      skills: ["Perception"], kits: ["smg", "club"], acFrom: ["Armoured jacket", "Armoured jacket", "Combat vest", "Hardshell"],
      traits: [{ name: "Calls it in", min: 1, text: "On first taking damage, reinforcements are dispatched. They arrive in 1d4 rounds." },
               { name: "Drilled", min: 5, text: "When an ally within 5 ft. is hit, it can use its reaction to give that ally +2 AC against the attack." }] },
    { id: "house-enforcer", name: "House Enforcer", cat: "house", role: "soldier",
      desc: "A House's muscle in bone-carved plate. Trained for holy ground.",
      scores: { Str: 16, Dex: 12, Con: 15, Int: 10, Wis: 13, Cha: 12 }, prime: "Str", acAdj: 1,
      skills: ["Intimidation"], kits: ["heavy", "pistol"], acFrom: "Bone-carved plate",
      powers: [{ name: "Collections notice", min: 1, text: "One creature that owes a debt: Wis save DC {dc} or frightened for 1 minute." }],
      traits: [{ name: "Consecrated", min: 1, text: "Unaffected by the sanctuary static on holy ground. They train for it." },
               { name: "Lien", min: 5, text: "Its first hit each turn on a frightened creature deals an extra {pb} damage." }] },
    { id: "corpo-lieutenant", name: "Corpo Lieutenant", cat: "house", role: "elite",
      desc: "Commands a House security detail. Smartlinked, patient, well paid.",
      scores: { Str: 15, Dex: 16, Con: 15, Int: 13, Wis: 14, Cha: 13 }, prime: "Dex", dcAbil: "Int",
      saves: ["Dex", "Wis"], skills: ["Perception", "Insight"], kits: ["rifle", "pistol"], acFrom: "Hardshell",
      powers: [{ name: "Suppressing fire", min: 1, text: "20-ft. cone: Dex save DC {dc} or half speed and disadvantage on attacks until their next turn." },
               { name: "Tactical order", min: 5, text: "Bonus action: one ally who can hear it makes one weapon attack with advantage." }],
      traits: [{ name: "Smartlinked", min: 1, text: "Ignores half cover." }] },
    { id: "thorn-collector", name: "Thorn Collector", cat: "house", role: "elite",
      desc: "House Thorn collects in person. Never raises their voice.",
      scores: { Str: 16, Dex: 14, Con: 15, Int: 13, Wis: 14, Cha: 16 }, prime: "Str", dcAbil: "Cha",
      saves: ["Str", "Wis", "Cha"], skills: ["Intimidation", "Insight", "Persuasion"], kits: ["blade", "pistol"], acFrom: "Full chrome",
      powers: [{ name: "Writ", min: 1, text: "One debtor within 30 ft.: Wis save DC {dc} or it can't move away from the Collector on its next turn." }],
      traits: [{ name: "Payment, counter-favour or duel", min: 1, text: "Offers all three before drawing. Accepts the first one offered." },
               { name: "The book remembers", min: 5, text: "Advantage on attacks against anyone with a debt on House Thorn's ledger." }],
      reactions: [{ name: "Riposte", min: 5, text: "When a creature misses it in melee, it makes one weapon attack against that creature." }] },
    { id: "house-knight", name: "House Knight", cat: "house", role: "boss",
      desc: "A House's champion in gold-lit chrome. Their oath is on the ledger.",
      scores: { Str: 18, Dex: 12, Con: 16, Int: 12, Wis: 14, Cha: 16 }, prime: "Str", dcAbil: "Cha",
      saves: ["Str", "Con", "Wis"], skills: ["Athletics", "Intimidation"], kits: ["heavy", "rifle"], acAdj: 1,
      acFrom: ["Knight's chrome", "Knight's chrome", "Gilded plate", "Gilded plate"],
      powers: [{ name: "Oath-light", min: 1, aoe: true, dice: ["2d6", "3d8", "5d8", "7d8"], text: "Recharge 5-6. 15-ft. cone of the Eye's gold light: Con save DC {dc}, {dmg} radiant damage and blinded until the end of its next turn; half and not blinded on a success." }],
      traits: [{ name: "Oathbound", min: 1, text: "Immune to being frightened while its House's colours are in sight." }] },
    { id: "corpo-suit", name: "Corpo Suit", cat: "house", role: "bystander",
      desc: "A House clerk or executive. Dangerous with a pen, not a gun.",
      scores: { Str: 9, Dex: 10, Con: 10, Int: 14, Wis: 12, Cha: 14 }, prime: "Dex", dcAbil: "Cha",
      skills: ["Persuasion", "Insight", "Deception"], kits: ["pistol"], acFrom: "A good suit",
      traits: [{ name: "Expensive to kill", min: 1, text: "Killing them costs Street Cred 2 and puts their House's standing down a step." }] },

    /* ============================== law & the watch ============================== */
    { id: "watch-patrol", name: "Watch Patrol", cat: "law", role: "minion",
      desc: "House Vigil's Watch, walking a rib with a lantern and a baton.",
      scores: { Str: 13, Dex: 12, Con: 12, Int: 10, Wis: 11, Cha: 10 }, prime: "Str",
      kits: ["club", "pistol"], acFrom: "Watch coat",
      traits: [{ name: "Whistle", min: 1, text: "One blast brings the rest of the patrol (1d4+1 more) in 1d4 rounds." }] },
    { id: "vigil-sergeant", name: "Vigil Sergeant", cat: "law", role: "soldier",
      desc: "Runs a Watch post. Knows every face on the rib, and every price.",
      scores: { Str: 15, Dex: 13, Con: 14, Int: 11, Wis: 13, Cha: 12 }, prime: "Str",
      skills: ["Insight", "Perception", "Intimidation"], kits: ["club", "shotgun"], acFrom: "Vigil half-plate",
      powers: [{ name: "Lockdown", min: 1, text: "Bonus action: seals the nearest lift or ward-door; it opens again only for a Vigil key or a DC {dc} check." }],
      traits: [{ name: "On the take", min: 1, text: "A bribe of 500 grams per level turns it away for a scene. Twice that, and it helps." }] },
    { id: "ward-keeper", name: "Ward-Keeper", cat: "law", role: "controller",
      desc: "Maintains the prayer-wards on the lifts and gates. Can close a street with a word.",
      scores: { Str: 9, Dex: 12, Con: 12, Int: 15, Wis: 15, Cha: 11 }, prime: "Wis",
      saves: ["Int", "Wis"], skills: ["Religion", "Technology"], kits: ["dart"], acFrom: "Ward-woven coat",
      powers: [{ name: "Ward-line", min: 1, text: "A 30-ft. line of warding appears: anyone crossing it makes a Wis save DC {dc} or stops and is restrained until the end of its turn." },
               { name: "Ward-burn", min: 5, dice: ["2d8", "3d8", "4d8", "6d8"], text: "One creature restrained by a ward: {dmg} radiant damage, no save." }] },
    { id: "lift-marshal", name: "Lift Marshal", cat: "law", role: "skirmisher",
      desc: "Rides the Spine's cars keeping order. Fights best in a moving box.",
      scores: { Str: 13, Dex: 15, Con: 13, Int: 11, Wis: 13, Cha: 10 }, prime: "Dex",
      skills: ["Acrobatics", "Perception"], kits: ["club", "pistol"], acFrom: "Marshal's harness",
      traits: [{ name: "Car legs", min: 1, text: "Never falls prone from a lurch, a stop or a push while on a lift." },
               { name: "Override", min: 5, text: "Action: stops, starts or drops the lift it's on by up to 60 ft." }] },

    /* ============================== tech & machines ============================== */
    { id: "combat-drone", name: "Combat Drone", cat: "tech", role: "skirmisher",
      desc: "A flying gun with a camera. Someone is watching through it.",
      scores: { Str: 10, Dex: 18, Con: 12, Int: 4, Wis: 10, Cha: 1 }, prime: "Dex", speed: "0 ft., fly 50 ft. (hover)",
      kits: ["slug"], acFrom: "Plating", immune: "poison, psychic", condImmune: "charmed, exhaustion, frightened, poisoned",
      senses: "darkvision 60 ft.",
      traits: [{ name: "Hardened", min: 1, text: "Technology DC {dc} to seize control for one round." },
               { name: "Dead air", min: 1, text: "On consecrated ground it falls and is disabled until moved off it." }] },
    { id: "security-turret", name: "Security Turret", cat: "tech", role: "soldier",
      desc: "Bolted to a wall, hungry for motion.",
      scores: { Str: 14, Dex: 14, Con: 16, Int: 2, Wis: 12, Cha: 1 }, prime: "Dex", speed: "0 ft.",
      kits: ["smg"], acAdj: 2, acFrom: "Armoured housing", immune: "poison, psychic",
      condImmune: "charmed, exhaustion, frightened, poisoned, prone", senses: "blindsight 60 ft.",
      traits: [{ name: "Motion tracker", min: 1, text: "Only fires at creatures that moved on their last turn." },
               { name: "Cut the power", min: 1, text: "A DC {dc} Technology check at its junction box turns it off." }] },
    { id: "netrunner", name: "Netrunner", cat: "tech", role: "controller",
      desc: "Their body is a slumped shape in a chair. The rest of them is in your implants.",
      scores: { Str: 8, Dex: 14, Con: 12, Int: 16, Wis: 12, Cha: 11 }, prime: "Int",
      saves: ["Int"], skills: ["Technology", "Investigation"], kits: ["pistol"], acFrom: "Nothing useful",
      powers: [{ name: "Icepick", min: 1, dice: ["2d8", "3d8", "5d8", "7d8"], text: "One creature with chrome or a smartlink within 120 ft.: Int save DC {dc}, {dmg} psychic damage, half on a success." },
               { name: "Lockout", min: 3, text: "One powered implant shuts down for 1 minute. Int save DC {dc} negates." },
               { name: "Hijack", min: 9, text: "One drone or turret within 120 ft. is theirs for 1 minute." }],
      traits: [{ name: "Jacked in", min: 1, text: "Its body is prone and helpless while running. Killing the body ends the run." },
               { name: "Dead air", min: 1, text: "On consecrated ground it can't run at all." }] },
    { id: "repo-mech", name: "Repo Mech", cat: "tech", role: "brute",
      desc: "House Reliquary's repossession rig. Built to take things back.",
      scores: { Str: 20, Dex: 8, Con: 18, Int: 3, Wis: 10, Cha: 1 }, prime: "Str", speed: "25 ft.",
      kits: ["chromefist"], acAdj: 3, acFrom: "Industrial frame", immune: "poison, psychic",
      condImmune: "charmed, exhaustion, frightened, poisoned",
      powers: [{ name: "Extract", min: 1, dice: ["2d6", "3d6", "4d6", "6d6"], text: "One grappled creature: Con save DC {dc} or {dmg} damage and one implant torn out (the GM picks)." }],
      traits: [{ name: "Grapple claws", min: 1, text: "A creature it hits with its fist is grappled (escape DC {dc})." }] },
    { id: "hunter-killer", name: "Hunter-Killer", cat: "tech", role: "elite",
      desc: "It has one name on its list. It will walk past everyone else to reach them.",
      scores: { Str: 18, Dex: 20, Con: 16, Int: 8, Wis: 14, Cha: 1 }, prime: "Dex", speed: "40 ft., fly 60 ft.",
      kits: ["slug", "claws"], acFrom: "Composite shell", immune: "poison, psychic",
      condImmune: "charmed, exhaustion, frightened, poisoned", senses: "truesight 30 ft., darkvision 120 ft.",
      powers: [{ name: "Target lock", min: 1, text: "Marks one creature. Advantage against it until it breaks line of sight." }],
      traits: [{ name: "Assigned", min: 1, text: "It ignores everyone but its target unless they stand in the way." }] },

    /* ============================== underworld ============================== */
    { id: "fixer", name: "Fixer", cat: "underworld", role: "support",
      desc: "Brokers jobs, favours and silence. Never the one holding the gun.",
      scores: { Str: 10, Dex: 12, Con: 12, Int: 14, Wis: 14, Cha: 16 }, prime: "Dex", dcAbil: "Cha",
      saves: ["Wis", "Cha"], skills: ["Persuasion", "Insight", "Deception"], kits: ["pistol"], acFrom: "Armoured vest under the coat",
      powers: [{ name: "Call in a favour", min: 1, text: "Once a day, 1d4 Gutter Gangers (at this level) arrive in 1d4 rounds." },
               { name: "Everyone has a price", min: 5, text: "One creature within 30 ft. that can hear it: Wis save DC {dc} or it stops attacking the Fixer for 1 minute, to listen." }] },
    { id: "hired-gun", name: "Hired Gun", cat: "underworld", role: "soldier",
      desc: "Bodyguard for a fence, a fixer or anyone who pays on time.",
      scores: { Str: 14, Dex: 15, Con: 14, Int: 10, Wis: 12, Cha: 10 }, prime: "Dex",
      skills: ["Perception", "Intimidation"], kits: ["pistol", "blade"], acFrom: "Combat vest",
      reactions: [{ name: "Bodyguard", min: 1, text: "When a creature within 5 ft. is attacked, it becomes the target instead." }] },
    { id: "smuggler", name: "Smuggler", cat: "underworld", role: "skirmisher",
      desc: "Moves things up the Spine that the Houses would rather stayed down.",
      scores: { Str: 11, Dex: 16, Con: 12, Int: 13, Wis: 12, Cha: 13 }, prime: "Dex",
      skills: ["Stealth", "Deception", "Sleight of Hand"], kits: ["knife", "smg"], acFrom: "Smuggler's coat",
      traits: [{ name: "Hidden compartments", min: 1, text: "Always has one more weapon or one more package than a search finds." },
               { name: "Slippery", min: 5, text: "Can Hide as a bonus action in dim light." }] },
    { id: "gutter-chemist", name: "Gutter Chemist", cat: "underworld", role: "controller",
      desc: "Cooks stims and gas in a Tallowgate back room. Carries samples.",
      scores: { Str: 9, Dex: 14, Con: 13, Int: 16, Wis: 11, Cha: 10 }, prime: "Int",
      skills: ["Medicine", "Investigation"], kits: ["dart"], acFrom: "Rubber apron",
      powers: [{ name: "Gas grenade", min: 1, aoe: true, dice: ["2d6", "3d6", "5d6", "7d6"], text: "20-ft. cloud within 60 ft.: Con save DC {dc}, {dmg} poison damage and poisoned for 1 round; half and not poisoned on a success." },
               { name: "Combat stim", min: 5, text: "Bonus action: one ally gains advantage on its next attack and {pb} temporary hit points." }] },
    { id: "assassin", name: "Assassin", cat: "underworld", role: "elite",
      desc: "Arrives as a waiter, a pilgrim or a lift operator. Leaves as nobody.",
      scores: { Str: 12, Dex: 18, Con: 14, Int: 13, Wis: 14, Cha: 12 }, prime: "Dex",
      saves: ["Dex", "Int"], skills: ["Stealth", "Deception", "Perception"], kits: ["knife", "sniper"], acFrom: "Nanoweave",
      traits: [{ name: "First strike", min: 1, text: "Advantage on attacks against any creature that hasn't acted yet in the fight; those hits deal an extra {dmg}.",
                 dice: ["2d6", "3d6", "5d6", "7d6"] },
               { name: "Evasion", min: 5, text: "On a successful Dex save for half damage, it takes none." }] },

    /* ============================== medical ============================== */
    { id: "ripperdoc", name: "Ripperdoc", cat: "medical", role: "support",
      desc: "Installs chrome, removes bullets, asks no questions.",
      scores: { Str: 10, Dex: 12, Con: 12, Int: 15, Wis: 14, Cha: 10 }, prime: "Int",
      skills: ["Medicine", "Technology"], kits: ["knife", "dart"], acFrom: "Apron",
      powers: [{ name: "Field surgery", min: 1, heal: true, dice: ["1d8", "2d8", "3d8", "4d8"], text: "One creature within 5 ft. regains {dmg} hit points." },
               { name: "Sedative jet", min: 1, text: "Ranged 15 ft.: Con save DC {dc} or poisoned for 1 minute." }] },
    { id: "bone-carver", name: "Bone-carver", cat: "medical", role: "controller",
      desc: "Carves implants from marrow. Knows exactly where your chrome is weakest.",
      scores: { Str: 11, Dex: 14, Con: 13, Int: 16, Wis: 14, Cha: 10 }, prime: "Int",
      skills: ["Medicine", "Technology", "Insight"], kits: ["knife"], acFrom: "Carver's leathers",
      powers: [{ name: "Unkey", min: 1, text: "One creature with implants within 30 ft.: Con save DC {dc} or one implant stops working until it finishes a short rest." },
               { name: "Graft-shock", min: 5, dice: ["2d8", "3d8", "4d8", "6d8"], text: "One creature with implants: Con save DC {dc}, {dmg} psychic damage, half on a success." }] },
    { id: "clinic-orderly", name: "Clinic Orderly", cat: "medical", role: "minion",
      desc: "Holds people down in a black clinic. Paid in painkillers.",
      scores: { Str: 14, Dex: 10, Con: 13, Int: 8, Wis: 10, Cha: 8 }, prime: "Str",
      kits: ["club"], acFrom: "Scrubs",
      traits: [{ name: "Restrain", min: 1, text: "Advantage on checks to grapple." }] },

    /* ============================== workers & civilians ============================== */
    { id: "civilian", name: "Civilian", cat: "workers", role: "bystander",
      desc: "Someone who was just there.",
      scores: { Str: 10, Dex: 10, Con: 10, Int: 10, Wis: 10, Cha: 10 }, prime: "Str",
      kits: ["unarmed"], acFrom: "Street clothes",
      powers: [{ name: "Run", min: 1, text: "Dashes for the nearest exit and screams." }] },
    { id: "marrowworks-driller", name: "Marrowworks Driller", cat: "workers", role: "brute",
      desc: "Three shifts, no windows. Strong from the drill, deaf from it too.",
      scores: { Str: 16, Dex: 10, Con: 15, Int: 9, Wis: 11, Cha: 10 }, prime: "Str",
      skills: ["Athletics"], kits: ["drill"], acFrom: "Work plating",
      traits: [{ name: "Deaf to it", min: 1, text: "Immune to thunder damage and to being deafened." },
               { name: "Crew", min: 5, text: "Advantage on attacks while another driller is within 10 ft." }] },
    { id: "lift-operator", name: "Lift Operator", cat: "workers", role: "bystander",
      desc: "One operator to a car, and the best-informed people in the city.",
      scores: { Str: 10, Dex: 13, Con: 11, Int: 12, Wis: 14, Cha: 12 }, prime: "Dex",
      skills: ["Perception", "Insight"], kits: ["club"], acFrom: "Operator's coat",
      traits: [{ name: "Heard it all", min: 1, text: "Knows one rumour about anyone who has ridden the Spine this week." },
               { name: "Emergency stop", min: 1, text: "Can stop the car between ribs, and will if threatened." }] },
    { id: "angry-crowd", name: "Angry Crowd", cat: "workers", role: "brute",
      desc: "Twenty people who have had enough. One creature, many hands.",
      scores: { Str: 14, Dex: 8, Con: 14, Int: 6, Wis: 10, Cha: 8 }, prime: "Str",
      kits: ["unarmed"], acAdj: -3, acFrom: "Numbers",
      condImmune: "charmed, frightened, grappled, paralysed, prone, stunned",
      traits: [{ name: "Swarm", min: 1, text: "Occupies a 20-ft. square; can enter hostile spaces. Deals half damage when below half its hit points." },
               { name: "Stampede", min: 1, text: "Everyone in its space at the start of its turn: Dex save DC {dc} or knocked prone." }] },

    /* ============================== god-touched ============================== */
    { id: "ichor-sick", name: "Ichor-sick", cat: "godtouched", role: "minion",
      desc: "Drank refinery run-off. Glows a little. Hungry a lot.",
      scores: { Str: 13, Dex: 10, Con: 14, Int: 4, Wis: 8, Cha: 4 }, prime: "Str",
      kits: ["claws"], acFrom: "Hardened skin", resist: "radiant", senses: "darkvision 60 ft.",
      traits: [{ name: "Burst", min: 1, text: "When it dies, creatures within 5 ft. take {pb} radiant damage." }] },
    { id: "remnant-ridden", name: "Remnant-ridden", cat: "godtouched", role: "skirmisher",
      desc: "Second-hand chrome whose last owner is still in there, driving.",
      scores: { Str: 12, Dex: 16, Con: 13, Int: 10, Wis: 10, Cha: 12 }, prime: "Dex",
      kits: ["claws", "pistol"], acFrom: "Someone else's plating",
      traits: [{ name: "Two minds", min: 1, text: "Advantage on saves against being charmed or frightened." },
               { name: "Wrong reflexes", min: 5, text: "Opportunity attacks against it have disadvantage." }] },
    { id: "marrow-horror", name: "Marrow Horror", cat: "godtouched", role: "brute",
      desc: "Something the drill woke. Bone that grew in the wrong direction.",
      scores: { Str: 18, Dex: 10, Con: 18, Int: 3, Wis: 12, Cha: 5 }, prime: "Str", speed: "30 ft., climb 30 ft.",
      kits: ["bone"], acAdj: 2, acFrom: "Living bone", resist: "piercing", senses: "tremorsense 60 ft.",
      traits: [{ name: "Regrowth", min: 1, text: "Regains {pb} hit points at the start of its turn unless it took fire or radiant damage since its last turn." },
               { name: "Grasp", min: 5, text: "A creature it hits is grappled (escape DC {dc})." }] },
    { id: "choir-fragment", name: "Choir Fragment", cat: "godtouched", role: "controller",
      desc: "A piece of the Cantor's song that got loose. It wants company.",
      scores: { Str: 8, Dex: 16, Con: 16, Int: 14, Wis: 18, Cha: 20 }, prime: "Cha", speed: "0 ft., fly 30 ft. (hover)",
      saves: ["Wis", "Cha"], kits: ["unarmed"], acFrom: "Not entirely there", immune: "psychic",
      condImmune: "charmed, frightened, prone", senses: "blindsight 60 ft.",
      powers: [{ name: "Chord", min: 1, aoe: true, dice: ["2d8", "4d8", "5d8", "7d8"], text: "All creatures within 20 ft.: Con save DC {dc}, {dmg} thunder damage and deafened, half and not deafened on a success." },
               { name: "Invitation", min: 1, text: "One creature that can hear it: Wis save DC {dc} or charmed, moving toward it on its turn." }],
      traits: [{ name: "Part of the song", min: 1, text: "While another Choir Fragment is within 60 ft., it has advantage on all saves." }] },
    { id: "the-warm-hand", name: "The Warm Hand", cat: "godtouched", role: "boss",
      desc: "A finger of the god being born. Gentle, until it closes.",
      scores: { Str: 22, Dex: 8, Con: 20, Int: 6, Wis: 16, Cha: 18 }, prime: "Str", dcAbil: "Con", speed: "20 ft.",
      saves: ["Str", "Con", "Wis"], kits: ["bone"], acAdj: 2, acFrom: "New bone", resist: "bludgeoning, piercing, slashing",
      immune: "psychic", condImmune: "charmed, frightened", senses: "tremorsense 120 ft.",
      powers: [{ name: "Close", min: 1, aoe: true, dice: ["3d8", "5d8", "7d8", "9d8"], text: "Recharge 5-6. Every creature within 15 ft.: Str save DC {dc} or {dmg} bludgeoning and restrained; half and free on a success." },
               { name: "Light", min: 5, text: "Every creature that can see it: Wis save DC {dc} or it can't attack the Hand on its next turn, for the wonder of it." }],
      traits: [{ name: "Birth", min: 1, text: "Every creature within 60 ft. that has seen a vision of the future has disadvantage on saves against it." }] }
  ]
};
